// Copyright 2026 jonathanberhe
// Licensed under the Apache License, Version 2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: vectordb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectionRequest_MetricType int32

const (
	CreateCollectionRequest_L2            CreateCollectionRequest_MetricType = 0
	CreateCollectionRequest_INNER_PRODUCT CreateCollectionRequest_MetricType = 1
	CreateCollectionRequest_COSINE        CreateCollectionRequest_MetricType = 2
)

// Enum value maps for CreateCollectionRequest_MetricType.
var (
	CreateCollectionRequest_MetricType_name = map[int32]string{
		0: "L2",
		1: "INNER_PRODUCT",
		2: "COSINE",
	}
	CreateCollectionRequest_MetricType_value = map[string]int32{
		"L2":            0,
		"INNER_PRODUCT": 1,
		"COSINE":        2,
	}
)

func (x CreateCollectionRequest_MetricType) Enum() *CreateCollectionRequest_MetricType {
	p := new(CreateCollectionRequest_MetricType)
	*p = x
	return p
}

func (x CreateCollectionRequest_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCollectionRequest_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[0].Descriptor()
}

func (CreateCollectionRequest_MetricType) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[0]
}

func (x CreateCollectionRequest_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCollectionRequest_MetricType.Descriptor instead.
func (CreateCollectionRequest_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{6, 0}
}

type CreateCollectionRequest_IndexType int32

const (
	CreateCollectionRequest_FLAT           CreateCollectionRequest_IndexType = 0
	CreateCollectionRequest_HNSW           CreateCollectionRequest_IndexType = 1
	CreateCollectionRequest_IVF_FLAT       CreateCollectionRequest_IndexType = 2
	CreateCollectionRequest_IVF_PQ         CreateCollectionRequest_IndexType = 3 // Inverted File with Product Quantization
	CreateCollectionRequest_IVF_SQ         CreateCollectionRequest_IndexType = 4 // Inverted File with Scalar Quantization
	CreateCollectionRequest_IVF_TURBOQUANT CreateCollectionRequest_IndexType = 5 // IVF + TurboQuant compression (sub-linear + extreme compression)
	CreateCollectionRequest_TURBOQUANT     CreateCollectionRequest_IndexType = 6 // TurboQuant online quantization (data-oblivious)
)

// Enum value maps for CreateCollectionRequest_IndexType.
var (
	CreateCollectionRequest_IndexType_name = map[int32]string{
		0: "FLAT",
		1: "HNSW",
		2: "IVF_FLAT",
		3: "IVF_PQ",
		4: "IVF_SQ",
		5: "IVF_TURBOQUANT",
		6: "TURBOQUANT",
	}
	CreateCollectionRequest_IndexType_value = map[string]int32{
		"FLAT":           0,
		"HNSW":           1,
		"IVF_FLAT":       2,
		"IVF_PQ":         3,
		"IVF_SQ":         4,
		"IVF_TURBOQUANT": 5,
		"TURBOQUANT":     6,
	}
)

func (x CreateCollectionRequest_IndexType) Enum() *CreateCollectionRequest_IndexType {
	p := new(CreateCollectionRequest_IndexType)
	*p = x
	return p
}

func (x CreateCollectionRequest_IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCollectionRequest_IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[1].Descriptor()
}

func (CreateCollectionRequest_IndexType) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[1]
}

func (x CreateCollectionRequest_IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCollectionRequest_IndexType.Descriptor instead.
func (CreateCollectionRequest_IndexType) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{6, 1}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[2]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{26, 0}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_vectordb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

// Sparse vector for learned sparse retrieval (SPLADE, etc.)
type SparseVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"` // Non-zero dimension indices (sorted ascending)
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`  // Corresponding non-zero values
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseVector) Reset() {
	*x = SparseVector{}
	mi := &file_vectordb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseVector) ProtoMessage() {}

func (x *SparseVector) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseVector.ProtoReflect.Descriptor instead.
func (*SparseVector) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{1}
}

func (x *SparseVector) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *SparseVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// Metadata value (supports multiple types)
type MetadataValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetadataValue_IntValue
	//	*MetadataValue_DoubleValue
	//	*MetadataValue_StringValue
	//	*MetadataValue_BoolValue
	Value         isMetadataValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValue) Reset() {
	*x = MetadataValue{}
	mi := &file_vectordb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValue) ProtoMessage() {}

func (x *MetadataValue) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValue.ProtoReflect.Descriptor instead.
func (*MetadataValue) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataValue) GetValue() isMetadataValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetadataValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetadataValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetadataValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MetadataValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MetadataValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isMetadataValue_Value interface {
	isMetadataValue_Value()
}

type MetadataValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetadataValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MetadataValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MetadataValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*MetadataValue_IntValue) isMetadataValue_Value() {}

func (*MetadataValue_DoubleValue) isMetadataValue_Value() {}

func (*MetadataValue_StringValue) isMetadataValue_Value() {}

func (*MetadataValue_BoolValue) isMetadataValue_Value() {}

// Metadata (key-value pairs)
type Metadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Fields        map[string]*MetadataValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_vectordb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetFields() map[string]*MetadataValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

type VectorWithId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // Optional metadata
	SparseVector  *SparseVector          `protobuf:"bytes,4,opt,name=sparse_vector,json=sparseVector,proto3" json:"sparse_vector,omitempty"` // Optional sparse vector for hybrid retrieval
	TtlSeconds    uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`      // Optional TTL in seconds (0 = no expiration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorWithId) Reset() {
	*x = VectorWithId{}
	mi := &file_vectordb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorWithId) ProtoMessage() {}

func (x *VectorWithId) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorWithId.ProtoReflect.Descriptor instead.
func (*VectorWithId) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{4}
}

func (x *VectorWithId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VectorWithId) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *VectorWithId) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VectorWithId) GetSparseVector() *SparseVector {
	if x != nil {
		return x.SparseVector
	}
	return nil
}

func (x *VectorWithId) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SearchResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // Optional: return metadata with results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultEntry) Reset() {
	*x = SearchResultEntry{}
	mi := &file_vectordb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultEntry) ProtoMessage() {}

func (x *SearchResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultEntry.ProtoReflect.Descriptor instead.
func (*SearchResultEntry) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResultEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResultEntry) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResultEntry) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateCollectionRequest struct {
	state          protoimpl.MessageState             `protogen:"open.v1"`
	CollectionName string                             `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Dimension      uint32                             `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric         CreateCollectionRequest_MetricType `protobuf:"varint,3,opt,name=metric,proto3,enum=gvdb.proto.CreateCollectionRequest_MetricType" json:"metric,omitempty"`
	IndexType      CreateCollectionRequest_IndexType  `protobuf:"varint,4,opt,name=index_type,json=indexType,proto3,enum=gvdb.proto.CreateCollectionRequest_IndexType" json:"index_type,omitempty"`
	NumShards      uint32                             `protobuf:"varint,5,opt,name=num_shards,json=numShards,proto3" json:"num_shards,omitempty"` // Number of shards (0 = default 1)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_vectordb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() CreateCollectionRequest_MetricType {
	if x != nil {
		return x.Metric
	}
	return CreateCollectionRequest_L2
}

func (x *CreateCollectionRequest) GetIndexType() CreateCollectionRequest_IndexType {
	if x != nil {
		return x.IndexType
	}
	return CreateCollectionRequest_FLAT
}

func (x *CreateCollectionRequest) GetNumShards() uint32 {
	if x != nil {
		return x.NumShards
	}
	return 0
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_vectordb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCollectionResponse) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CreateCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DropCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_vectordb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{8}
}

func (x *DropCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_vectordb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{9}
}

func (x *DropCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_vectordb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{10}
}

type CollectionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionId   uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Dimension      uint32                 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	MetricType     string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	VectorCount    uint64                 `protobuf:"varint,5,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_vectordb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{11}
}

func (x *CollectionInfo) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CollectionInfo) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionInfo) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionInfo) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *CollectionInfo) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_vectordb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{12}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type InsertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Vectors        []*VectorWithId        `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_vectordb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{13}
}

func (x *InsertRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *InsertRequest) GetVectors() []*VectorWithId {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount uint64                 `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_vectordb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{14}
}

func (x *InsertResponse) GetInsertedCount() uint64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *InsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	QueryVector    *Vector                `protobuf:"bytes,2,opt,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK           uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter         string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`                                        // Optional: SQL-like filter expression (e.g., "price < 100 AND brand = 'Nike'")
	ReturnMetadata bool                   `protobuf:"varint,5,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"` // Optional: whether to return metadata in results
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_vectordb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{15}
}

func (x *SearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchRequest) GetQueryVector() *Vector {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SearchRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs   float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_vectordb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResponse) GetResults() []*SearchResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type GetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Ids            []uint64               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`                                      // Vector IDs to retrieve
	ReturnMetadata bool                   `protobuf:"varint,3,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"` // Optional: whether to return metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_vectordb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{17}
}

func (x *GetRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GetRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*VectorWithId        `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`                                      // Retrieved vectors (may be fewer than requested if some IDs not found)
	NotFoundIds   []uint64               `protobuf:"varint,2,rep,packed,name=not_found_ids,json=notFoundIds,proto3" json:"not_found_ids,omitempty"` // IDs that were not found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_vectordb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{18}
}

func (x *GetResponse) GetVectors() []*VectorWithId {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *GetResponse) GetNotFoundIds() []uint64 {
	if x != nil {
		return x.NotFoundIds
	}
	return nil
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Ids            []uint64               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"` // Vector IDs to delete
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_vectordb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *DeleteRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  uint64                 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`       // Number of vectors actually deleted
	NotFoundIds   []uint64               `protobuf:"varint,2,rep,packed,name=not_found_ids,json=notFoundIds,proto3" json:"not_found_ids,omitempty"` // IDs that were not found
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_vectordb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteResponse) GetDeletedCount() uint64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteResponse) GetNotFoundIds() []uint64 {
	if x != nil {
		return x.NotFoundIds
	}
	return nil
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateMetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Id             uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`            // Vector ID to update
	Metadata       *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"` // New metadata (replaces existing)
	Merge          bool                   `protobuf:"varint,4,opt,name=merge,proto3" json:"merge,omitempty"`      // If true, merge with existing metadata. If false, replace completely.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_vectordb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateMetadataRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *UpdateMetadataRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMetadataRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateMetadataRequest) GetMerge() bool {
	if x != nil {
		return x.Merge
	}
	return false
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"` // Whether the update succeeded
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_vectordb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateMetadataResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *UpdateMetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListVectorsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectionName  string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Limit           uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // Page size (default 20)
	Offset          uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Offset for pagination
	IncludeMetadata bool                   `protobuf:"varint,4,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListVectorsRequest) Reset() {
	*x = ListVectorsRequest{}
	mi := &file_vectordb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVectorsRequest) ProtoMessage() {}

func (x *ListVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVectorsRequest.ProtoReflect.Descriptor instead.
func (*ListVectorsRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{23}
}

func (x *ListVectorsRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *ListVectorsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVectorsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListVectorsRequest) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type ListVectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*VectorWithId        `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVectorsResponse) Reset() {
	*x = ListVectorsResponse{}
	mi := &file_vectordb_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVectorsResponse) ProtoMessage() {}

func (x *ListVectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVectorsResponse.ProtoReflect.Descriptor instead.
func (*ListVectorsResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{24}
}

func (x *ListVectorsResponse) GetVectors() []*VectorWithId {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *ListVectorsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListVectorsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_vectordb_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{25}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=gvdb.proto.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_vectordb_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{26}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_vectordb_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{27}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalVectors     uint64                 `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`
	TotalCollections uint64                 `protobuf:"varint,2,opt,name=total_collections,json=totalCollections,proto3" json:"total_collections,omitempty"`
	TotalQueries     uint64                 `protobuf:"varint,3,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	AvgQueryTimeMs   float32                `protobuf:"fixed32,4,opt,name=avg_query_time_ms,json=avgQueryTimeMs,proto3" json:"avg_query_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_vectordb_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{28}
}

func (x *GetStatsResponse) GetTotalVectors() uint64 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *GetStatsResponse) GetTotalCollections() uint64 {
	if x != nil {
		return x.TotalCollections
	}
	return 0
}

func (x *GetStatsResponse) GetTotalQueries() uint64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *GetStatsResponse) GetAvgQueryTimeMs() float32 {
	if x != nil {
		return x.AvgQueryTimeMs
	}
	return 0
}

type UpsertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Vectors        []*VectorWithId        `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_vectordb_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{29}
}

func (x *UpsertRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *UpsertRequest) GetVectors() []*VectorWithId {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type UpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpsertedCount uint64                 `protobuf:"varint,1,opt,name=upserted_count,json=upsertedCount,proto3" json:"upserted_count,omitempty"`
	InsertedCount uint64                 `protobuf:"varint,2,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"` // New vectors inserted
	UpdatedCount  uint64                 `protobuf:"varint,3,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`    // Existing vectors replaced
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_vectordb_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{30}
}

func (x *UpsertResponse) GetUpsertedCount() uint64 {
	if x != nil {
		return x.UpsertedCount
	}
	return 0
}

func (x *UpsertResponse) GetInsertedCount() uint64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *UpsertResponse) GetUpdatedCount() uint64 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *UpsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RangeSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	QueryVector    *Vector                `protobuf:"bytes,2,opt,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	Radius         float32                `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"` // Distance threshold
	Filter         string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`   // Optional metadata filter
	ReturnMetadata bool                   `protobuf:"varint,5,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"`
	MaxResults     uint32                 `protobuf:"varint,6,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // Limit results (0 = unlimited, default 1000)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RangeSearchRequest) Reset() {
	*x = RangeSearchRequest{}
	mi := &file_vectordb_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSearchRequest) ProtoMessage() {}

func (x *RangeSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSearchRequest.ProtoReflect.Descriptor instead.
func (*RangeSearchRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{31}
}

func (x *RangeSearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *RangeSearchRequest) GetQueryVector() *Vector {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *RangeSearchRequest) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *RangeSearchRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *RangeSearchRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

func (x *RangeSearchRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type RangeSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs   float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeSearchResponse) Reset() {
	*x = RangeSearchResponse{}
	mi := &file_vectordb_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSearchResponse) ProtoMessage() {}

func (x *RangeSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeSearchResponse.ProtoReflect.Descriptor instead.
func (*RangeSearchResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{32}
}

func (x *RangeSearchResponse) GetResults() []*SearchResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RangeSearchResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type HybridSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	QueryVector    *Vector                `protobuf:"bytes,2,opt,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // Dense vector query
	TextQuery      string                 `protobuf:"bytes,3,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"`       // Text query for BM25
	TopK           uint32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter         string                 `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"` // Optional metadata filter
	ReturnMetadata bool                   `protobuf:"varint,6,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"`
	VectorWeight   float32                `protobuf:"fixed32,7,opt,name=vector_weight,json=vectorWeight,proto3" json:"vector_weight,omitempty"`  // 0.0-1.0 (default: 0.5 if both set)
	TextWeight     float32                `protobuf:"fixed32,8,opt,name=text_weight,json=textWeight,proto3" json:"text_weight,omitempty"`        // 0.0-1.0 (default: 0.5 if both set)
	TextField      string                 `protobuf:"bytes,9,opt,name=text_field,json=textField,proto3" json:"text_field,omitempty"`             // Metadata field for BM25 (default: "text")
	SparseQuery    *SparseVector          `protobuf:"bytes,10,opt,name=sparse_query,json=sparseQuery,proto3" json:"sparse_query,omitempty"`      // Optional sparse query vector
	SparseWeight   float32                `protobuf:"fixed32,11,opt,name=sparse_weight,json=sparseWeight,proto3" json:"sparse_weight,omitempty"` // Weight for sparse results in RRF (0 = disabled)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_vectordb_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{33}
}

func (x *HybridSearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *HybridSearchRequest) GetQueryVector() *Vector {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *HybridSearchRequest) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

func (x *HybridSearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *HybridSearchRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *HybridSearchRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

func (x *HybridSearchRequest) GetVectorWeight() float32 {
	if x != nil {
		return x.VectorWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetTextWeight() float32 {
	if x != nil {
		return x.TextWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetTextField() string {
	if x != nil {
		return x.TextField
	}
	return ""
}

func (x *HybridSearchRequest) GetSparseQuery() *SparseVector {
	if x != nil {
		return x.SparseQuery
	}
	return nil
}

func (x *HybridSearchRequest) GetSparseWeight() float32 {
	if x != nil {
		return x.SparseWeight
	}
	return 0
}

type HybridSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs   float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_vectordb_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{34}
}

func (x *HybridSearchResponse) GetResults() []*SearchResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *HybridSearchResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

var File_vectordb_proto protoreflect.FileDescriptor

const file_vectordb_proto_rawDesc = "" +
	"\n" +
	"\x0evectordb.proto\x12\n" +
	"gvdb.proto\">\n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\"@\n" +
	"\fSparseVector\x12\x18\n" +
	"\aindices\x18\x01 \x03(\rR\aindices\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\"\xa2\x01\n" +
	"\rMetadataValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValueB\a\n" +
	"\x05value\"\x9a\x01\n" +
	"\bMetadata\x128\n" +
	"\x06fields\x18\x01 \x03(\v2 .gvdb.proto.Metadata.FieldsEntryR\x06fields\x1aT\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.gvdb.proto.MetadataValueR\x05value:\x028\x01\"\xdc\x01\n" +
	"\fVectorWithId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12*\n" +
	"\x06vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\x06vector\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.gvdb.proto.MetadataR\bmetadata\x12=\n" +
	"\rsparse_vector\x18\x04 \x01(\v2\x18.gvdb.proto.SparseVectorR\fsparseVector\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\"q\n" +
	"\x11SearchResultEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.gvdb.proto.MetadataR\bmetadata\"\xb5\x03\n" +
	"\x17CreateCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12F\n" +
	"\x06metric\x18\x03 \x01(\x0e2..gvdb.proto.CreateCollectionRequest.MetricTypeR\x06metric\x12L\n" +
	"\n" +
	"index_type\x18\x04 \x01(\x0e2-.gvdb.proto.CreateCollectionRequest.IndexTypeR\tindexType\x12\x1d\n" +
	"\n" +
	"num_shards\x18\x05 \x01(\rR\tnumShards\"3\n" +
	"\n" +
	"MetricType\x12\x06\n" +
	"\x02L2\x10\x00\x12\x11\n" +
	"\rINNER_PRODUCT\x10\x01\x12\n" +
	"\n" +
	"\x06COSINE\x10\x02\"i\n" +
	"\tIndexType\x12\b\n" +
	"\x04FLAT\x10\x00\x12\b\n" +
	"\x04HNSW\x10\x01\x12\f\n" +
	"\bIVF_FLAT\x10\x02\x12\n" +
	"\n" +
	"\x06IVF_PQ\x10\x03\x12\n" +
	"\n" +
	"\x06IVF_SQ\x10\x04\x12\x12\n" +
	"\x0eIVF_TURBOQUANT\x10\x05\x12\x0e\n" +
	"\n" +
	"TURBOQUANT\x10\x06\"Y\n" +
	"\x18CreateCollectionResponse\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x15DropCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\"2\n" +
	"\x16DropCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x16ListCollectionsRequest\"\xc0\x01\n" +
	"\x0eCollectionInfo\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\rR\tdimension\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12!\n" +
	"\fvector_count\x18\x05 \x01(\x04R\vvectorCount\"W\n" +
	"\x17ListCollectionsResponse\x12<\n" +
	"\vcollections\x18\x01 \x03(\v2\x1a.gvdb.proto.CollectionInfoR\vcollections\"l\n" +
	"\rInsertRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x122\n" +
	"\avectors\x18\x02 \x03(\v2\x18.gvdb.proto.VectorWithIdR\avectors\"Q\n" +
	"\x0eInsertResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x04R\rinsertedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x01\n" +
	"\rSearchRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x125\n" +
	"\fquery_vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12'\n" +
	"\x0freturn_metadata\x18\x05 \x01(\bR\x0ereturnMetadata\"m\n" +
	"\x0eSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.gvdb.proto.SearchResultEntryR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs\"p\n" +
	"\n" +
	"GetRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x04R\x03ids\x12'\n" +
	"\x0freturn_metadata\x18\x03 \x01(\bR\x0ereturnMetadata\"e\n" +
	"\vGetResponse\x122\n" +
	"\avectors\x18\x01 \x03(\v2\x18.gvdb.proto.VectorWithIdR\avectors\x12\"\n" +
	"\rnot_found_ids\x18\x02 \x03(\x04R\vnotFoundIds\"J\n" +
	"\rDeleteRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x04R\x03ids\"s\n" +
	"\x0eDeleteResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x04R\fdeletedCount\x12\"\n" +
	"\rnot_found_ids\x18\x02 \x03(\x04R\vnotFoundIds\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x98\x01\n" +
	"\x15UpdateMetadataRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.gvdb.proto.MetadataR\bmetadata\x12\x14\n" +
	"\x05merge\x18\x04 \x01(\bR\x05merge\"L\n" +
	"\x16UpdateMetadataResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\x12ListVectorsRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12)\n" +
	"\x10include_metadata\x18\x04 \x01(\bR\x0fincludeMetadata\"\x85\x01\n" +
	"\x13ListVectorsResponse\x122\n" +
	"\avectors\x18\x01 \x03(\v2\x18.gvdb.proto.VectorWithIdR\avectors\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x14\n" +
	"\x12HealthCheckRequest\"\xa4\x01\n" +
	"\x13HealthCheckResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.gvdb.proto.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\x11\n" +
	"\x0fGetStatsRequest\"\xb4\x01\n" +
	"\x10GetStatsResponse\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x04R\ftotalVectors\x12+\n" +
	"\x11total_collections\x18\x02 \x01(\x04R\x10totalCollections\x12#\n" +
	"\rtotal_queries\x18\x03 \x01(\x04R\ftotalQueries\x12)\n" +
	"\x11avg_query_time_ms\x18\x04 \x01(\x02R\x0eavgQueryTimeMs\"l\n" +
	"\rUpsertRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x122\n" +
	"\avectors\x18\x02 \x03(\v2\x18.gvdb.proto.VectorWithIdR\avectors\"\x9d\x01\n" +
	"\x0eUpsertResponse\x12%\n" +
	"\x0eupserted_count\x18\x01 \x01(\x04R\rupsertedCount\x12%\n" +
	"\x0einserted_count\x18\x02 \x01(\x04R\rinsertedCount\x12#\n" +
	"\rupdated_count\x18\x03 \x01(\x04R\fupdatedCount\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xee\x01\n" +
	"\x12RangeSearchRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x125\n" +
	"\fquery_vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\vqueryVector\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x02R\x06radius\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12'\n" +
	"\x0freturn_metadata\x18\x05 \x01(\bR\x0ereturnMetadata\x12\x1f\n" +
	"\vmax_results\x18\x06 \x01(\rR\n" +
	"maxResults\"r\n" +
	"\x13RangeSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.gvdb.proto.SearchResultEntryR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs\"\xb1\x03\n" +
	"\x13HybridSearchRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x125\n" +
	"\fquery_vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\vqueryVector\x12\x1d\n" +
	"\n" +
	"text_query\x18\x03 \x01(\tR\ttextQuery\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\rR\x04topK\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12'\n" +
	"\x0freturn_metadata\x18\x06 \x01(\bR\x0ereturnMetadata\x12#\n" +
	"\rvector_weight\x18\a \x01(\x02R\fvectorWeight\x12\x1f\n" +
	"\vtext_weight\x18\b \x01(\x02R\n" +
	"textWeight\x12\x1d\n" +
	"\n" +
	"text_field\x18\t \x01(\tR\ttextField\x12;\n" +
	"\fsparse_query\x18\n" +
	" \x01(\v2\x18.gvdb.proto.SparseVectorR\vsparseQuery\x12#\n" +
	"\rsparse_weight\x18\v \x01(\x02R\fsparseWeight\"s\n" +
	"\x14HybridSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.gvdb.proto.SearchResultEntryR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs2\x8d\t\n" +
	"\x0fVectorDBService\x12]\n" +
	"\x10CreateCollection\x12#.gvdb.proto.CreateCollectionRequest\x1a$.gvdb.proto.CreateCollectionResponse\x12W\n" +
	"\x0eDropCollection\x12!.gvdb.proto.DropCollectionRequest\x1a\".gvdb.proto.DropCollectionResponse\x12Z\n" +
	"\x0fListCollections\x12\".gvdb.proto.ListCollectionsRequest\x1a#.gvdb.proto.ListCollectionsResponse\x12?\n" +
	"\x06Insert\x12\x19.gvdb.proto.InsertRequest\x1a\x1a.gvdb.proto.InsertResponse\x12G\n" +
	"\fStreamInsert\x12\x19.gvdb.proto.InsertRequest\x1a\x1a.gvdb.proto.InsertResponse(\x01\x12?\n" +
	"\x06Upsert\x12\x19.gvdb.proto.UpsertRequest\x1a\x1a.gvdb.proto.UpsertResponse\x12?\n" +
	"\x06Search\x12\x19.gvdb.proto.SearchRequest\x1a\x1a.gvdb.proto.SearchResponse\x12N\n" +
	"\vRangeSearch\x12\x1e.gvdb.proto.RangeSearchRequest\x1a\x1f.gvdb.proto.RangeSearchResponse\x126\n" +
	"\x03Get\x12\x16.gvdb.proto.GetRequest\x1a\x17.gvdb.proto.GetResponse\x12?\n" +
	"\x06Delete\x12\x19.gvdb.proto.DeleteRequest\x1a\x1a.gvdb.proto.DeleteResponse\x12W\n" +
	"\x0eUpdateMetadata\x12!.gvdb.proto.UpdateMetadataRequest\x1a\".gvdb.proto.UpdateMetadataResponse\x12N\n" +
	"\vListVectors\x12\x1e.gvdb.proto.ListVectorsRequest\x1a\x1f.gvdb.proto.ListVectorsResponse\x12Q\n" +
	"\fHybridSearch\x12\x1f.gvdb.proto.HybridSearchRequest\x1a .gvdb.proto.HybridSearchResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.gvdb.proto.HealthCheckRequest\x1a\x1f.gvdb.proto.HealthCheckResponse\x12E\n" +
	"\bGetStats\x12\x1b.gvdb.proto.GetStatsRequest\x1a\x1c.gvdb.proto.GetStatsResponseB\x1bZ\x19gvdb/integration-tests/pbb\x06proto3"

var (
	file_vectordb_proto_rawDescOnce sync.Once
	file_vectordb_proto_rawDescData []byte
)

func file_vectordb_proto_rawDescGZIP() []byte {
	file_vectordb_proto_rawDescOnce.Do(func() {
		file_vectordb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vectordb_proto_rawDesc), len(file_vectordb_proto_rawDesc)))
	})
	return file_vectordb_proto_rawDescData
}

var file_vectordb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vectordb_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_vectordb_proto_goTypes = []any{
	(CreateCollectionRequest_MetricType)(0), // 0: gvdb.proto.CreateCollectionRequest.MetricType
	(CreateCollectionRequest_IndexType)(0),  // 1: gvdb.proto.CreateCollectionRequest.IndexType
	(HealthCheckResponse_Status)(0),         // 2: gvdb.proto.HealthCheckResponse.Status
	(*Vector)(nil),                          // 3: gvdb.proto.Vector
	(*SparseVector)(nil),                    // 4: gvdb.proto.SparseVector
	(*MetadataValue)(nil),                   // 5: gvdb.proto.MetadataValue
	(*Metadata)(nil),                        // 6: gvdb.proto.Metadata
	(*VectorWithId)(nil),                    // 7: gvdb.proto.VectorWithId
	(*SearchResultEntry)(nil),               // 8: gvdb.proto.SearchResultEntry
	(*CreateCollectionRequest)(nil),         // 9: gvdb.proto.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),        // 10: gvdb.proto.CreateCollectionResponse
	(*DropCollectionRequest)(nil),           // 11: gvdb.proto.DropCollectionRequest
	(*DropCollectionResponse)(nil),          // 12: gvdb.proto.DropCollectionResponse
	(*ListCollectionsRequest)(nil),          // 13: gvdb.proto.ListCollectionsRequest
	(*CollectionInfo)(nil),                  // 14: gvdb.proto.CollectionInfo
	(*ListCollectionsResponse)(nil),         // 15: gvdb.proto.ListCollectionsResponse
	(*InsertRequest)(nil),                   // 16: gvdb.proto.InsertRequest
	(*InsertResponse)(nil),                  // 17: gvdb.proto.InsertResponse
	(*SearchRequest)(nil),                   // 18: gvdb.proto.SearchRequest
	(*SearchResponse)(nil),                  // 19: gvdb.proto.SearchResponse
	(*GetRequest)(nil),                      // 20: gvdb.proto.GetRequest
	(*GetResponse)(nil),                     // 21: gvdb.proto.GetResponse
	(*DeleteRequest)(nil),                   // 22: gvdb.proto.DeleteRequest
	(*DeleteResponse)(nil),                  // 23: gvdb.proto.DeleteResponse
	(*UpdateMetadataRequest)(nil),           // 24: gvdb.proto.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil),          // 25: gvdb.proto.UpdateMetadataResponse
	(*ListVectorsRequest)(nil),              // 26: gvdb.proto.ListVectorsRequest
	(*ListVectorsResponse)(nil),             // 27: gvdb.proto.ListVectorsResponse
	(*HealthCheckRequest)(nil),              // 28: gvdb.proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 29: gvdb.proto.HealthCheckResponse
	(*GetStatsRequest)(nil),                 // 30: gvdb.proto.GetStatsRequest
	(*GetStatsResponse)(nil),                // 31: gvdb.proto.GetStatsResponse
	(*UpsertRequest)(nil),                   // 32: gvdb.proto.UpsertRequest
	(*UpsertResponse)(nil),                  // 33: gvdb.proto.UpsertResponse
	(*RangeSearchRequest)(nil),              // 34: gvdb.proto.RangeSearchRequest
	(*RangeSearchResponse)(nil),             // 35: gvdb.proto.RangeSearchResponse
	(*HybridSearchRequest)(nil),             // 36: gvdb.proto.HybridSearchRequest
	(*HybridSearchResponse)(nil),            // 37: gvdb.proto.HybridSearchResponse
	nil,                                     // 38: gvdb.proto.Metadata.FieldsEntry
}
var file_vectordb_proto_depIdxs = []int32{
	38, // 0: gvdb.proto.Metadata.fields:type_name -> gvdb.proto.Metadata.FieldsEntry
	3,  // 1: gvdb.proto.VectorWithId.vector:type_name -> gvdb.proto.Vector
	6,  // 2: gvdb.proto.VectorWithId.metadata:type_name -> gvdb.proto.Metadata
	4,  // 3: gvdb.proto.VectorWithId.sparse_vector:type_name -> gvdb.proto.SparseVector
	6,  // 4: gvdb.proto.SearchResultEntry.metadata:type_name -> gvdb.proto.Metadata
	0,  // 5: gvdb.proto.CreateCollectionRequest.metric:type_name -> gvdb.proto.CreateCollectionRequest.MetricType
	1,  // 6: gvdb.proto.CreateCollectionRequest.index_type:type_name -> gvdb.proto.CreateCollectionRequest.IndexType
	14, // 7: gvdb.proto.ListCollectionsResponse.collections:type_name -> gvdb.proto.CollectionInfo
	7,  // 8: gvdb.proto.InsertRequest.vectors:type_name -> gvdb.proto.VectorWithId
	3,  // 9: gvdb.proto.SearchRequest.query_vector:type_name -> gvdb.proto.Vector
	8,  // 10: gvdb.proto.SearchResponse.results:type_name -> gvdb.proto.SearchResultEntry
	7,  // 11: gvdb.proto.GetResponse.vectors:type_name -> gvdb.proto.VectorWithId
	6,  // 12: gvdb.proto.UpdateMetadataRequest.metadata:type_name -> gvdb.proto.Metadata
	7,  // 13: gvdb.proto.ListVectorsResponse.vectors:type_name -> gvdb.proto.VectorWithId
	2,  // 14: gvdb.proto.HealthCheckResponse.status:type_name -> gvdb.proto.HealthCheckResponse.Status
	7,  // 15: gvdb.proto.UpsertRequest.vectors:type_name -> gvdb.proto.VectorWithId
	3,  // 16: gvdb.proto.RangeSearchRequest.query_vector:type_name -> gvdb.proto.Vector
	8,  // 17: gvdb.proto.RangeSearchResponse.results:type_name -> gvdb.proto.SearchResultEntry
	3,  // 18: gvdb.proto.HybridSearchRequest.query_vector:type_name -> gvdb.proto.Vector
	4,  // 19: gvdb.proto.HybridSearchRequest.sparse_query:type_name -> gvdb.proto.SparseVector
	8,  // 20: gvdb.proto.HybridSearchResponse.results:type_name -> gvdb.proto.SearchResultEntry
	5,  // 21: gvdb.proto.Metadata.FieldsEntry.value:type_name -> gvdb.proto.MetadataValue
	9,  // 22: gvdb.proto.VectorDBService.CreateCollection:input_type -> gvdb.proto.CreateCollectionRequest
	11, // 23: gvdb.proto.VectorDBService.DropCollection:input_type -> gvdb.proto.DropCollectionRequest
	13, // 24: gvdb.proto.VectorDBService.ListCollections:input_type -> gvdb.proto.ListCollectionsRequest
	16, // 25: gvdb.proto.VectorDBService.Insert:input_type -> gvdb.proto.InsertRequest
	16, // 26: gvdb.proto.VectorDBService.StreamInsert:input_type -> gvdb.proto.InsertRequest
	32, // 27: gvdb.proto.VectorDBService.Upsert:input_type -> gvdb.proto.UpsertRequest
	18, // 28: gvdb.proto.VectorDBService.Search:input_type -> gvdb.proto.SearchRequest
	34, // 29: gvdb.proto.VectorDBService.RangeSearch:input_type -> gvdb.proto.RangeSearchRequest
	20, // 30: gvdb.proto.VectorDBService.Get:input_type -> gvdb.proto.GetRequest
	22, // 31: gvdb.proto.VectorDBService.Delete:input_type -> gvdb.proto.DeleteRequest
	24, // 32: gvdb.proto.VectorDBService.UpdateMetadata:input_type -> gvdb.proto.UpdateMetadataRequest
	26, // 33: gvdb.proto.VectorDBService.ListVectors:input_type -> gvdb.proto.ListVectorsRequest
	36, // 34: gvdb.proto.VectorDBService.HybridSearch:input_type -> gvdb.proto.HybridSearchRequest
	28, // 35: gvdb.proto.VectorDBService.HealthCheck:input_type -> gvdb.proto.HealthCheckRequest
	30, // 36: gvdb.proto.VectorDBService.GetStats:input_type -> gvdb.proto.GetStatsRequest
	10, // 37: gvdb.proto.VectorDBService.CreateCollection:output_type -> gvdb.proto.CreateCollectionResponse
	12, // 38: gvdb.proto.VectorDBService.DropCollection:output_type -> gvdb.proto.DropCollectionResponse
	15, // 39: gvdb.proto.VectorDBService.ListCollections:output_type -> gvdb.proto.ListCollectionsResponse
	17, // 40: gvdb.proto.VectorDBService.Insert:output_type -> gvdb.proto.InsertResponse
	17, // 41: gvdb.proto.VectorDBService.StreamInsert:output_type -> gvdb.proto.InsertResponse
	33, // 42: gvdb.proto.VectorDBService.Upsert:output_type -> gvdb.proto.UpsertResponse
	19, // 43: gvdb.proto.VectorDBService.Search:output_type -> gvdb.proto.SearchResponse
	35, // 44: gvdb.proto.VectorDBService.RangeSearch:output_type -> gvdb.proto.RangeSearchResponse
	21, // 45: gvdb.proto.VectorDBService.Get:output_type -> gvdb.proto.GetResponse
	23, // 46: gvdb.proto.VectorDBService.Delete:output_type -> gvdb.proto.DeleteResponse
	25, // 47: gvdb.proto.VectorDBService.UpdateMetadata:output_type -> gvdb.proto.UpdateMetadataResponse
	27, // 48: gvdb.proto.VectorDBService.ListVectors:output_type -> gvdb.proto.ListVectorsResponse
	37, // 49: gvdb.proto.VectorDBService.HybridSearch:output_type -> gvdb.proto.HybridSearchResponse
	29, // 50: gvdb.proto.VectorDBService.HealthCheck:output_type -> gvdb.proto.HealthCheckResponse
	31, // 51: gvdb.proto.VectorDBService.GetStats:output_type -> gvdb.proto.GetStatsResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_vectordb_proto_init() }
func file_vectordb_proto_init() {
	if File_vectordb_proto != nil {
		return
	}
	file_vectordb_proto_msgTypes[2].OneofWrappers = []any{
		(*MetadataValue_IntValue)(nil),
		(*MetadataValue_DoubleValue)(nil),
		(*MetadataValue_StringValue)(nil),
		(*MetadataValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vectordb_proto_rawDesc), len(file_vectordb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vectordb_proto_goTypes,
		DependencyIndexes: file_vectordb_proto_depIdxs,
		EnumInfos:         file_vectordb_proto_enumTypes,
		MessageInfos:      file_vectordb_proto_msgTypes,
	}.Build()
	File_vectordb_proto = out.File
	file_vectordb_proto_goTypes = nil
	file_vectordb_proto_depIdxs = nil
}
