apiVersion: v2
name: gvdb
description: Distributed vector database for similarity search
type: application
version: 0.2.0 # x-release-please-version
appVersion: "0.2.0" # x-release-please-version
home: https://github.com/JonathanBerhe/gvdb
sources:
  - https://github.com/JonathanBerhe/gvdb
maintainers:
  - name: Jonathan Berhe
    url: https://github.com/JonathanBerhe
