// Copyright 2026 jonathanberhe
// Licensed under the Apache License, Version 2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal.proto

package gvdbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_UNKNOWN     NodeType = 0
	NodeType_NODE_TYPE_COORDINATOR NodeType = 1
	NodeType_NODE_TYPE_DATA_NODE   NodeType = 2
	NodeType_NODE_TYPE_QUERY_NODE  NodeType = 3
	NodeType_NODE_TYPE_PROXY       NodeType = 4
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNKNOWN",
		1: "NODE_TYPE_COORDINATOR",
		2: "NODE_TYPE_DATA_NODE",
		3: "NODE_TYPE_QUERY_NODE",
		4: "NODE_TYPE_PROXY",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNKNOWN":     0,
		"NODE_TYPE_COORDINATOR": 1,
		"NODE_TYPE_DATA_NODE":   2,
		"NODE_TYPE_QUERY_NODE":  3,
		"NODE_TYPE_PROXY":       4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	// Default / unset — node has not yet reported a status.
	NodeStatus_NODE_STATUS_UNKNOWN NodeStatus = 0
	// Node is initializing and not yet ready to serve traffic.
	NodeStatus_NODE_STATUS_STARTING NodeStatus = 1
	// Node is healthy and accepting requests.
	NodeStatus_NODE_STATUS_READY NodeStatus = 2
	// Node is operational but under high load.
	NodeStatus_NODE_STATUS_BUSY NodeStatus = 3
	// Node is operational with reduced capacity (partial failure).
	NodeStatus_NODE_STATUS_DEGRADED NodeStatus = 4
	// Node is unreachable or has failed.
	NodeStatus_NODE_STATUS_DOWN NodeStatus = 5
	// Node is shutting down gracefully. Sent as a final heartbeat from the node
	// so the coordinator stops routing new work to it without waiting for
	// heartbeat timeout (roadmap 0b.1).
	NodeStatus_NODE_STATUS_DRAINING NodeStatus = 6
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNKNOWN",
		1: "NODE_STATUS_STARTING",
		2: "NODE_STATUS_READY",
		3: "NODE_STATUS_BUSY",
		4: "NODE_STATUS_DEGRADED",
		5: "NODE_STATUS_DOWN",
		6: "NODE_STATUS_DRAINING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNKNOWN":  0,
		"NODE_STATUS_STARTING": 1,
		"NODE_STATUS_READY":    2,
		"NODE_STATUS_BUSY":     3,
		"NODE_STATUS_DEGRADED": 4,
		"NODE_STATUS_DOWN":     5,
		"NODE_STATUS_DRAINING": 6,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

type NodeInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NodeId      uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType    NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=gvdb.proto.internal.NodeType" json:"node_type,omitempty"`
	GrpcAddress string                 `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"`
	RaftAddress string                 `protobuf:"bytes,4,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"` // Only for coordinators
	Status      NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=gvdb.proto.internal.NodeStatus" json:"status,omitempty"`
	// Resource information
	MemoryUsedBytes  uint64 `protobuf:"varint,6,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64 `protobuf:"varint,7,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskUsedBytes    uint64 `protobuf:"varint,8,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   uint64 `protobuf:"varint,9,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	// Performance metrics
	TotalRequests uint64  `protobuf:"varint,10,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	AvgLatencyMs  float32 `protobuf:"fixed32,11,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	ErrorCount    uint32  `protobuf:"varint,12,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeInfo) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNKNOWN
}

func (x *NodeInfo) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *NodeInfo) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *NodeInfo) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNKNOWN
}

func (x *NodeInfo) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeInfo) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeInfo) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeInfo) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeInfo) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *NodeInfo) GetAvgLatencyMs() float32 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *NodeInfo) GetErrorCount() uint32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

type ShardAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeIds       []uint32               `protobuf:"varint,2,rep,packed,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`              // Replica nodes for this shard
	PrimaryNodeId uint32                 `protobuf:"varint,3,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"` // Primary node for writes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAssignment) Reset() {
	*x = ShardAssignment{}
	mi := &file_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAssignment) ProtoMessage() {}

func (x *ShardAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAssignment.ProtoReflect.Descriptor instead.
func (*ShardAssignment) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{1}
}

func (x *ShardAssignment) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ShardAssignment) GetNodeIds() []uint32 {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *ShardAssignment) GetPrimaryNodeId() uint32 {
	if x != nil {
		return x.PrimaryNodeId
	}
	return 0
}

type AssignShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       uint32                 `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	NodeId        uint32                 `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignShardRequest) Reset() {
	*x = AssignShardRequest{}
	mi := &file_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShardRequest) ProtoMessage() {}

func (x *AssignShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShardRequest.ProtoReflect.Descriptor instead.
func (*AssignShardRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{2}
}

func (x *AssignShardRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AssignShardRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AssignShardRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type AssignShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignShardResponse) Reset() {
	*x = AssignShardResponse{}
	mi := &file_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignShardResponse) ProtoMessage() {}

func (x *AssignShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignShardResponse.ProtoReflect.Descriptor instead.
func (*AssignShardResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{3}
}

func (x *AssignShardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignShardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetShardAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 0 means all collections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardAssignmentsRequest) Reset() {
	*x = GetShardAssignmentsRequest{}
	mi := &file_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardAssignmentsRequest) ProtoMessage() {}

func (x *GetShardAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*GetShardAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{4}
}

func (x *GetShardAssignmentsRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

type GetShardAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*ShardAssignment     `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShardAssignmentsResponse) Reset() {
	*x = GetShardAssignmentsResponse{}
	mi := &file_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShardAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShardAssignmentsResponse) ProtoMessage() {}

func (x *GetShardAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShardAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*GetShardAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{5}
}

func (x *GetShardAssignmentsResponse) GetAssignments() []*ShardAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type RebalanceShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 0 means all collections
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceShardsRequest) Reset() {
	*x = RebalanceShardsRequest{}
	mi := &file_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceShardsRequest) ProtoMessage() {}

func (x *RebalanceShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceShardsRequest.ProtoReflect.Descriptor instead.
func (*RebalanceShardsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{6}
}

func (x *RebalanceShardsRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

type RebalanceShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardsMoved   uint32                 `protobuf:"varint,1,opt,name=shards_moved,json=shardsMoved,proto3" json:"shards_moved,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceShardsResponse) Reset() {
	*x = RebalanceShardsResponse{}
	mi := &file_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceShardsResponse) ProtoMessage() {}

func (x *RebalanceShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceShardsResponse.ProtoReflect.Descriptor instead.
func (*RebalanceShardsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{7}
}

func (x *RebalanceShardsResponse) GetShardsMoved() uint32 {
	if x != nil {
		return x.ShardsMoved
	}
	return 0
}

func (x *RebalanceShardsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint64                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	CollectionId  uint32                 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	ShardId       uint32                 `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	VectorCount   uint64                 `protobuf:"varint,4,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsSealed      bool                   `protobuf:"varint,6,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	SealedAt      int64                  `protobuf:"varint,8,opt,name=sealed_at,json=sealedAt,proto3" json:"sealed_at,omitempty"`    // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{8}
}

func (x *SegmentInfo) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *SegmentInfo) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *SegmentInfo) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *SegmentInfo) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *SegmentInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *SegmentInfo) GetIsSealed() bool {
	if x != nil {
		return x.IsSealed
	}
	return false
}

func (x *SegmentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SegmentInfo) GetSealedAt() int64 {
	if x != nil {
		return x.SealedAt
	}
	return 0
}

type ReplicateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentInfo   *SegmentInfo           `protobuf:"bytes,1,opt,name=segment_info,json=segmentInfo,proto3" json:"segment_info,omitempty"`
	TargetNodeId  uint32                 `protobuf:"varint,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	SegmentData   []byte                 `protobuf:"bytes,3,opt,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"` // Serialized segment data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateSegmentRequest) Reset() {
	*x = ReplicateSegmentRequest{}
	mi := &file_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateSegmentRequest) ProtoMessage() {}

func (x *ReplicateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateSegmentRequest.ProtoReflect.Descriptor instead.
func (*ReplicateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{9}
}

func (x *ReplicateSegmentRequest) GetSegmentInfo() *SegmentInfo {
	if x != nil {
		return x.SegmentInfo
	}
	return nil
}

func (x *ReplicateSegmentRequest) GetTargetNodeId() uint32 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

func (x *ReplicateSegmentRequest) GetSegmentData() []byte {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

type ReplicateSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateSegmentResponse) Reset() {
	*x = ReplicateSegmentResponse{}
	mi := &file_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateSegmentResponse) ProtoMessage() {}

func (x *ReplicateSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateSegmentResponse.ProtoReflect.Descriptor instead.
func (*ReplicateSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicateSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateSegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint64                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentRequest) Reset() {
	*x = GetSegmentRequest{}
	mi := &file_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentRequest) ProtoMessage() {}

func (x *GetSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentRequest.ProtoReflect.Descriptor instead.
func (*GetSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{11}
}

func (x *GetSegmentRequest) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type GetSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentInfo   *SegmentInfo           `protobuf:"bytes,1,opt,name=segment_info,json=segmentInfo,proto3" json:"segment_info,omitempty"`
	SegmentData   []byte                 `protobuf:"bytes,2,opt,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSegmentResponse) Reset() {
	*x = GetSegmentResponse{}
	mi := &file_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSegmentResponse) ProtoMessage() {}

func (x *GetSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSegmentResponse.ProtoReflect.Descriptor instead.
func (*GetSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{12}
}

func (x *GetSegmentResponse) GetSegmentInfo() *SegmentInfo {
	if x != nil {
		return x.SegmentInfo
	}
	return nil
}

func (x *GetSegmentResponse) GetSegmentData() []byte {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

type ListSegmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"` // 0 means all collections
	ShardId       uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`                // 0 means all shards
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsRequest) Reset() {
	*x = ListSegmentsRequest{}
	mi := &file_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsRequest) ProtoMessage() {}

func (x *ListSegmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsRequest.ProtoReflect.Descriptor instead.
func (*ListSegmentsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{13}
}

func (x *ListSegmentsRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ListSegmentsRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type ListSegmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*SegmentInfo         `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSegmentsResponse) Reset() {
	*x = ListSegmentsResponse{}
	mi := &file_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSegmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSegmentsResponse) ProtoMessage() {}

func (x *ListSegmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSegmentsResponse.ProtoReflect.Descriptor instead.
func (*ListSegmentsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{14}
}

func (x *ListSegmentsResponse) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type DeleteSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint64                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Delete even if replicas exist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentRequest) Reset() {
	*x = DeleteSegmentRequest{}
	mi := &file_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentRequest) ProtoMessage() {}

func (x *DeleteSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSegmentRequest) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *DeleteSegmentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSegmentResponse) Reset() {
	*x = DeleteSegmentResponse{}
	mi := &file_internal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSegmentResponse) ProtoMessage() {}

func (x *DeleteSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSegmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint64                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	CollectionId  uint32                 `protobuf:"varint,2,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Dimension     uint32                 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	MetricType    string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"` // "L2", "INNER_PRODUCT", "COSINE"
	IndexType     string                 `protobuf:"bytes,5,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`    // "FLAT", "HNSW", "IVF_FLAT", "IVF_PQ", "IVF_SQ"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentRequest) Reset() {
	*x = CreateSegmentRequest{}
	mi := &file_internal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentRequest) ProtoMessage() {}

func (x *CreateSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentRequest.ProtoReflect.Descriptor instead.
func (*CreateSegmentRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{17}
}

func (x *CreateSegmentRequest) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *CreateSegmentRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CreateSegmentRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateSegmentRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *CreateSegmentRequest) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

type CreateSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SegmentId     uint64                 `protobuf:"varint,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // Echo back for confirmation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSegmentResponse) Reset() {
	*x = CreateSegmentResponse{}
	mi := &file_internal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSegmentResponse) ProtoMessage() {}

func (x *CreateSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSegmentResponse.ProtoReflect.Descriptor instead.
func (*CreateSegmentResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{18}
}

func (x *CreateSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSegmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateSegmentResponse) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

type CollectionMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CollectionId     uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	CollectionName   string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Dimension        uint32                 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	MetricType       string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	IndexType        string                 `protobuf:"bytes,5,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	VectorCount      uint64                 `protobuf:"varint,6,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	ShardCount       uint32                 `protobuf:"varint,8,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	ShardAssignments []*ShardAssignment     `protobuf:"bytes,9,rep,name=shard_assignments,json=shardAssignments,proto3" json:"shard_assignments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectionMetadata) Reset() {
	*x = CollectionMetadata{}
	mi := &file_internal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionMetadata) ProtoMessage() {}

func (x *CollectionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionMetadata.ProtoReflect.Descriptor instead.
func (*CollectionMetadata) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{19}
}

func (x *CollectionMetadata) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CollectionMetadata) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionMetadata) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionMetadata) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *CollectionMetadata) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *CollectionMetadata) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *CollectionMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CollectionMetadata) GetShardCount() uint32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

func (x *CollectionMetadata) GetShardAssignments() []*ShardAssignment {
	if x != nil {
		return x.ShardAssignments
	}
	return nil
}

type SyncMetadataRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            uint32                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastSyncTimestamp int64                  `protobuf:"varint,2,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"` // Request changes after this timestamp
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncMetadataRequest) Reset() {
	*x = SyncMetadataRequest{}
	mi := &file_internal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMetadataRequest) ProtoMessage() {}

func (x *SyncMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMetadataRequest.ProtoReflect.Descriptor instead.
func (*SyncMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{20}
}

func (x *SyncMetadataRequest) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SyncMetadataRequest) GetLastSyncTimestamp() int64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

type SyncMetadataResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Collections      []*CollectionMetadata  `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	ShardAssignments []*ShardAssignment     `protobuf:"bytes,2,rep,name=shard_assignments,json=shardAssignments,proto3" json:"shard_assignments,omitempty"`
	CurrentTimestamp int64                  `protobuf:"varint,3,opt,name=current_timestamp,json=currentTimestamp,proto3" json:"current_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncMetadataResponse) Reset() {
	*x = SyncMetadataResponse{}
	mi := &file_internal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMetadataResponse) ProtoMessage() {}

func (x *SyncMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMetadataResponse.ProtoReflect.Descriptor instead.
func (*SyncMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{21}
}

func (x *SyncMetadataResponse) GetCollections() []*CollectionMetadata {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *SyncMetadataResponse) GetShardAssignments() []*ShardAssignment {
	if x != nil {
		return x.ShardAssignments
	}
	return nil
}

func (x *SyncMetadataResponse) GetCurrentTimestamp() int64 {
	if x != nil {
		return x.CurrentTimestamp
	}
	return 0
}

type GetCollectionMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetCollectionMetadataRequest_CollectionId
	//	*GetCollectionMetadataRequest_CollectionName
	Identifier    isGetCollectionMetadataRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionMetadataRequest) Reset() {
	*x = GetCollectionMetadataRequest{}
	mi := &file_internal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionMetadataRequest) ProtoMessage() {}

func (x *GetCollectionMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{22}
}

func (x *GetCollectionMetadataRequest) GetIdentifier() isGetCollectionMetadataRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetCollectionMetadataRequest) GetCollectionId() uint32 {
	if x != nil {
		if x, ok := x.Identifier.(*GetCollectionMetadataRequest_CollectionId); ok {
			return x.CollectionId
		}
	}
	return 0
}

func (x *GetCollectionMetadataRequest) GetCollectionName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCollectionMetadataRequest_CollectionName); ok {
			return x.CollectionName
		}
	}
	return ""
}

type isGetCollectionMetadataRequest_Identifier interface {
	isGetCollectionMetadataRequest_Identifier()
}

type GetCollectionMetadataRequest_CollectionId struct {
	CollectionId uint32 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3,oneof"`
}

type GetCollectionMetadataRequest_CollectionName struct {
	CollectionName string `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3,oneof"`
}

func (*GetCollectionMetadataRequest_CollectionId) isGetCollectionMetadataRequest_Identifier() {}

func (*GetCollectionMetadataRequest_CollectionName) isGetCollectionMetadataRequest_Identifier() {}

type GetCollectionMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *CollectionMetadata    `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionMetadataResponse) Reset() {
	*x = GetCollectionMetadataResponse{}
	mi := &file_internal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionMetadataResponse) ProtoMessage() {}

func (x *GetCollectionMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetCollectionMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{23}
}

func (x *GetCollectionMetadataResponse) GetMetadata() *CollectionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCollectionMetadataResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type RouteQueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	QueryVector    []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK           uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter         string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	ReturnMetadata bool                   `protobuf:"varint,5,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"`
	// When true, the coordinator may return a non-primary replica as the
	// target for a shard if the primary is draining. Proxies set this for
	// read operations where stale-but-live replicas are acceptable. Writes
	// must always go to the primary and should leave this false (roadmap
	// 0b.1 — proper primary migration is 0b.3).
	PreferRoutableReplica bool `protobuf:"varint,6,opt,name=prefer_routable_replica,json=preferRoutableReplica,proto3" json:"prefer_routable_replica,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RouteQueryRequest) Reset() {
	*x = RouteQueryRequest{}
	mi := &file_internal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueryRequest) ProtoMessage() {}

func (x *RouteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueryRequest.ProtoReflect.Descriptor instead.
func (*RouteQueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{24}
}

func (x *RouteQueryRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *RouteQueryRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *RouteQueryRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RouteQueryRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *RouteQueryRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

func (x *RouteQueryRequest) GetPreferRoutableReplica() bool {
	if x != nil {
		return x.PreferRoutableReplica
	}
	return false
}

type RouteQueryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TargetShardIds      []uint32               `protobuf:"varint,1,rep,packed,name=target_shard_ids,json=targetShardIds,proto3" json:"target_shard_ids,omitempty"`
	TargetNodeIds       []uint32               `protobuf:"varint,2,rep,packed,name=target_node_ids,json=targetNodeIds,proto3" json:"target_node_ids,omitempty"`
	TargetNodeAddresses []string               `protobuf:"bytes,3,rep,name=target_node_addresses,json=targetNodeAddresses,proto3" json:"target_node_addresses,omitempty"`
	CollectionId        uint32                 `protobuf:"varint,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RouteQueryResponse) Reset() {
	*x = RouteQueryResponse{}
	mi := &file_internal_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteQueryResponse) ProtoMessage() {}

func (x *RouteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteQueryResponse.ProtoReflect.Descriptor instead.
func (*RouteQueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{25}
}

func (x *RouteQueryResponse) GetTargetShardIds() []uint32 {
	if x != nil {
		return x.TargetShardIds
	}
	return nil
}

func (x *RouteQueryResponse) GetTargetNodeIds() []uint32 {
	if x != nil {
		return x.TargetNodeIds
	}
	return nil
}

func (x *RouteQueryResponse) GetTargetNodeAddresses() []string {
	if x != nil {
		return x.TargetNodeAddresses
	}
	return nil
}

func (x *RouteQueryResponse) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

type ExecuteShardQueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionId   uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	ShardId        uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	QueryVector    []float32              `protobuf:"fixed32,3,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK           uint32                 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filter         string                 `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	ReturnMetadata bool                   `protobuf:"varint,6,opt,name=return_metadata,json=returnMetadata,proto3" json:"return_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteShardQueryRequest) Reset() {
	*x = ExecuteShardQueryRequest{}
	mi := &file_internal_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteShardQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteShardQueryRequest) ProtoMessage() {}

func (x *ExecuteShardQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteShardQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteShardQueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{26}
}

func (x *ExecuteShardQueryRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ExecuteShardQueryRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ExecuteShardQueryRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *ExecuteShardQueryRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ExecuteShardQueryRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ExecuteShardQueryRequest) GetReturnMetadata() bool {
	if x != nil {
		return x.ReturnMetadata
	}
	return false
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_internal_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{27}
}

func (x *SearchResult) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResult) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecuteShardQueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Results        []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs    float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	VectorsScanned uint32                 `protobuf:"varint,3,opt,name=vectors_scanned,json=vectorsScanned,proto3" json:"vectors_scanned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteShardQueryResponse) Reset() {
	*x = ExecuteShardQueryResponse{}
	mi := &file_internal_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteShardQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteShardQueryResponse) ProtoMessage() {}

func (x *ExecuteShardQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteShardQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteShardQueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{28}
}

func (x *ExecuteShardQueryResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteShardQueryResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

func (x *ExecuteShardQueryResponse) GetVectorsScanned() uint32 {
	if x != nil {
		return x.VectorsScanned
	}
	return 0
}

type TransferDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	ShardId       uint32                 `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	SourceNodeId  uint32                 `protobuf:"varint,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId  uint32                 `protobuf:"varint,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferDataRequest) Reset() {
	*x = TransferDataRequest{}
	mi := &file_internal_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferDataRequest) ProtoMessage() {}

func (x *TransferDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferDataRequest.ProtoReflect.Descriptor instead.
func (*TransferDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{29}
}

func (x *TransferDataRequest) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *TransferDataRequest) GetShardId() uint32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *TransferDataRequest) GetSourceNodeId() uint32 {
	if x != nil {
		return x.SourceNodeId
	}
	return 0
}

func (x *TransferDataRequest) GetTargetNodeId() uint32 {
	if x != nil {
		return x.TargetNodeId
	}
	return 0
}

type TransferDataResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VectorsTransferred uint64                 `protobuf:"varint,2,opt,name=vectors_transferred,json=vectorsTransferred,proto3" json:"vectors_transferred,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferDataResponse) Reset() {
	*x = TransferDataResponse{}
	mi := &file_internal_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferDataResponse) ProtoMessage() {}

func (x *TransferDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferDataResponse.ProtoReflect.Descriptor instead.
func (*TransferDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{30}
}

func (x *TransferDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferDataResponse) GetVectorsTransferred() uint64 {
	if x != nil {
		return x.VectorsTransferred
	}
	return 0
}

func (x *TransferDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{31}
}

func (x *HeartbeatRequest) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Timestamp    int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Coordinator can send instructions in heartbeat response
	AssignedShards  []uint32 `protobuf:"varint,3,rep,packed,name=assigned_shards,json=assignedShards,proto3" json:"assigned_shards,omitempty"`
	ShouldRebalance bool     `protobuf:"varint,4,opt,name=should_rebalance,json=shouldRebalance,proto3" json:"should_rebalance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{32}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetAssignedShards() []uint32 {
	if x != nil {
		return x.AssignedShards
	}
	return nil
}

func (x *HeartbeatResponse) GetShouldRebalance() bool {
	if x != nil {
		return x.ShouldRebalance
	}
	return false
}

type GetClusterHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterHealthRequest) Reset() {
	*x = GetClusterHealthRequest{}
	mi := &file_internal_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthRequest) ProtoMessage() {}

func (x *GetClusterHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthRequest.ProtoReflect.Descriptor instead.
func (*GetClusterHealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{33}
}

type GetClusterHealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Nodes          []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalShards    uint32                 `protobuf:"varint,2,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`
	HealthyShards  uint32                 `protobuf:"varint,3,opt,name=healthy_shards,json=healthyShards,proto3" json:"healthy_shards,omitempty"`
	DegradedShards uint32                 `protobuf:"varint,4,opt,name=degraded_shards,json=degradedShards,proto3" json:"degraded_shards,omitempty"`
	ClusterStatus  string                 `protobuf:"bytes,5,opt,name=cluster_status,json=clusterStatus,proto3" json:"cluster_status,omitempty"` // "healthy", "degraded", "critical"
	// Unix-ms timestamp of the most recently completed auto-rebalance. Zero
	// when no rebalance has happened on this coordinator's watch (roadmap
	// 0b.6.E). Sourced from Coordinator::GetLastAutoRebalance().
	LastRebalanceUnixMs int64 `protobuf:"varint,6,opt,name=last_rebalance_unix_ms,json=lastRebalanceUnixMs,proto3" json:"last_rebalance_unix_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetClusterHealthResponse) Reset() {
	*x = GetClusterHealthResponse{}
	mi := &file_internal_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterHealthResponse) ProtoMessage() {}

func (x *GetClusterHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterHealthResponse.ProtoReflect.Descriptor instead.
func (*GetClusterHealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{34}
}

func (x *GetClusterHealthResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetClusterHealthResponse) GetTotalShards() uint32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *GetClusterHealthResponse) GetHealthyShards() uint32 {
	if x != nil {
		return x.HealthyShards
	}
	return 0
}

func (x *GetClusterHealthResponse) GetDegradedShards() uint32 {
	if x != nil {
		return x.DegradedShards
	}
	return 0
}

func (x *GetClusterHealthResponse) GetClusterStatus() string {
	if x != nil {
		return x.ClusterStatus
	}
	return ""
}

func (x *GetClusterHealthResponse) GetLastRebalanceUnixMs() int64 {
	if x != nil {
		return x.LastRebalanceUnixMs
	}
	return 0
}

type GetLeaderInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderInfoRequest) Reset() {
	*x = GetLeaderInfoRequest{}
	mi := &file_internal_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderInfoRequest) ProtoMessage() {}

func (x *GetLeaderInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{35}
}

type GetLeaderInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raft node id of the current leader. -1 or 0 when unknown / no leader.
	LeaderId int32 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	// Best-effort resolved "pod-name" (or endpoint) for the leader. Empty when
	// the coordinator cannot resolve the id to a known address (e.g. during
	// startup before NodeRegistry has seen the leader pod).
	LeaderAddress string `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	// Current Raft term seen by the responding coordinator.
	CurrentTerm uint64 `protobuf:"varint,3,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	// True when the responding coordinator is itself the leader.
	IsLeaderSelf  bool `protobuf:"varint,4,opt,name=is_leader_self,json=isLeaderSelf,proto3" json:"is_leader_self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderInfoResponse) Reset() {
	*x = GetLeaderInfoResponse{}
	mi := &file_internal_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderInfoResponse) ProtoMessage() {}

func (x *GetLeaderInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{36}
}

func (x *GetLeaderInfoResponse) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *GetLeaderInfoResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *GetLeaderInfoResponse) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *GetLeaderInfoResponse) GetIsLeaderSelf() bool {
	if x != nil {
		return x.IsLeaderSelf
	}
	return false
}

type GetTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // How many timestamps to allocate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampRequest) Reset() {
	*x = GetTimestampRequest{}
	mi := &file_internal_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampRequest) ProtoMessage() {}

func (x *GetTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampRequest.ProtoReflect.Descriptor instead.
func (*GetTimestampRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{37}
}

func (x *GetTimestampRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTimestampResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartTimestamp uint64                 `protobuf:"varint,1,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	EndTimestamp   uint64                 `protobuf:"varint,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"` // Inclusive range [start, end]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTimestampResponse) Reset() {
	*x = GetTimestampResponse{}
	mi := &file_internal_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampResponse) ProtoMessage() {}

func (x *GetTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampResponse.ProtoReflect.Descriptor instead.
func (*GetTimestampResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_rawDescGZIP(), []int{38}
}

func (x *GetTimestampResponse) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *GetTimestampResponse) GetEndTimestamp() uint64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

var File_internal_proto protoreflect.FileDescriptor

const file_internal_proto_rawDesc = "" +
	"\n" +
	"\x0einternal.proto\x12\x13gvdb.proto.internal\x1a\x0evectordb.proto\"\xf8\x03\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12:\n" +
	"\tnode_type\x18\x02 \x01(\x0e2\x1d.gvdb.proto.internal.NodeTypeR\bnodeType\x12!\n" +
	"\fgrpc_address\x18\x03 \x01(\tR\vgrpcAddress\x12!\n" +
	"\fraft_address\x18\x04 \x01(\tR\vraftAddress\x127\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1f.gvdb.proto.internal.NodeStatusR\x06status\x12*\n" +
	"\x11memory_used_bytes\x18\x06 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\a \x01(\x04R\x10memoryTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\b \x01(\x04R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\t \x01(\x04R\x0ediskTotalBytes\x12%\n" +
	"\x0etotal_requests\x18\n" +
	" \x01(\x04R\rtotalRequests\x12$\n" +
	"\x0eavg_latency_ms\x18\v \x01(\x02R\favgLatencyMs\x12\x1f\n" +
	"\verror_count\x18\f \x01(\rR\n" +
	"errorCount\"o\n" +
	"\x0fShardAssignment\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x19\n" +
	"\bnode_ids\x18\x02 \x03(\rR\anodeIds\x12&\n" +
	"\x0fprimary_node_id\x18\x03 \x01(\rR\rprimaryNodeId\"g\n" +
	"\x12AssignShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\rR\ashardId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\rR\x06nodeId\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\"I\n" +
	"\x13AssignShardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x1aGetShardAssignmentsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\"e\n" +
	"\x1bGetShardAssignmentsResponse\x12F\n" +
	"\vassignments\x18\x01 \x03(\v2$.gvdb.proto.internal.ShardAssignmentR\vassignments\"=\n" +
	"\x16RebalanceShardsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\"V\n" +
	"\x17RebalanceShardsResponse\x12!\n" +
	"\fshards_moved\x18\x01 \x01(\rR\vshardsMoved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x02\n" +
	"\vSegmentInfo\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\x04R\tsegmentId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\rR\fcollectionId\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\rR\ashardId\x12!\n" +
	"\fvector_count\x18\x04 \x01(\x04R\vvectorCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12\x1b\n" +
	"\tis_sealed\x18\x06 \x01(\bR\bisSealed\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tsealed_at\x18\b \x01(\x03R\bsealedAt\"\xa7\x01\n" +
	"\x17ReplicateSegmentRequest\x12C\n" +
	"\fsegment_info\x18\x01 \x01(\v2 .gvdb.proto.internal.SegmentInfoR\vsegmentInfo\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\rR\ftargetNodeId\x12!\n" +
	"\fsegment_data\x18\x03 \x01(\fR\vsegmentData\"N\n" +
	"\x18ReplicateSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x11GetSegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\x04R\tsegmentId\"|\n" +
	"\x12GetSegmentResponse\x12C\n" +
	"\fsegment_info\x18\x01 \x01(\v2 .gvdb.proto.internal.SegmentInfoR\vsegmentInfo\x12!\n" +
	"\fsegment_data\x18\x02 \x01(\fR\vsegmentData\"U\n" +
	"\x13ListSegmentsRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId\"T\n" +
	"\x14ListSegmentsResponse\x12<\n" +
	"\bsegments\x18\x01 \x03(\v2 .gvdb.proto.internal.SegmentInfoR\bsegments\"K\n" +
	"\x14DeleteSegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\x04R\tsegmentId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"K\n" +
	"\x15DeleteSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\x14CreateSegmentRequest\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\x04R\tsegmentId\x12#\n" +
	"\rcollection_id\x18\x02 \x01(\rR\fcollectionId\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\rR\tdimension\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12\x1d\n" +
	"\n" +
	"index_type\x18\x05 \x01(\tR\tindexType\"j\n" +
	"\x15CreateSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\x04R\tsegmentId\"\xf6\x02\n" +
	"\x12CollectionMetadata\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\rR\tdimension\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12\x1d\n" +
	"\n" +
	"index_type\x18\x05 \x01(\tR\tindexType\x12!\n" +
	"\fvector_count\x18\x06 \x01(\x04R\vvectorCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vshard_count\x18\b \x01(\rR\n" +
	"shardCount\x12Q\n" +
	"\x11shard_assignments\x18\t \x03(\v2$.gvdb.proto.internal.ShardAssignmentR\x10shardAssignments\"^\n" +
	"\x13SyncMetadataRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\rR\x06nodeId\x12.\n" +
	"\x13last_sync_timestamp\x18\x02 \x01(\x03R\x11lastSyncTimestamp\"\xe1\x01\n" +
	"\x14SyncMetadataResponse\x12I\n" +
	"\vcollections\x18\x01 \x03(\v2'.gvdb.proto.internal.CollectionMetadataR\vcollections\x12Q\n" +
	"\x11shard_assignments\x18\x02 \x03(\v2$.gvdb.proto.internal.ShardAssignmentR\x10shardAssignments\x12+\n" +
	"\x11current_timestamp\x18\x03 \x01(\x03R\x10currentTimestamp\"~\n" +
	"\x1cGetCollectionMetadataRequest\x12%\n" +
	"\rcollection_id\x18\x01 \x01(\rH\x00R\fcollectionId\x12)\n" +
	"\x0fcollection_name\x18\x02 \x01(\tH\x00R\x0ecollectionNameB\f\n" +
	"\n" +
	"identifier\"z\n" +
	"\x1dGetCollectionMetadataResponse\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.gvdb.proto.internal.CollectionMetadataR\bmetadata\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xed\x01\n" +
	"\x11RouteQueryRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12'\n" +
	"\x0freturn_metadata\x18\x05 \x01(\bR\x0ereturnMetadata\x126\n" +
	"\x17prefer_routable_replica\x18\x06 \x01(\bR\x15preferRoutableReplica\"\xbf\x01\n" +
	"\x12RouteQueryResponse\x12(\n" +
	"\x10target_shard_ids\x18\x01 \x03(\rR\x0etargetShardIds\x12&\n" +
	"\x0ftarget_node_ids\x18\x02 \x03(\rR\rtargetNodeIds\x122\n" +
	"\x15target_node_addresses\x18\x03 \x03(\tR\x13targetNodeAddresses\x12#\n" +
	"\rcollection_id\x18\x04 \x01(\rR\fcollectionId\"\xd3\x01\n" +
	"\x18ExecuteShardQueryRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId\x12!\n" +
	"\fquery_vector\x18\x03 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\rR\x04topK\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12'\n" +
	"\x0freturn_metadata\x18\x06 \x01(\bR\x0ereturnMetadata\"l\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.gvdb.proto.MetadataR\bmetadata\"\xa5\x01\n" +
	"\x19ExecuteShardQueryResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.gvdb.proto.internal.SearchResultR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs\x12'\n" +
	"\x0fvectors_scanned\x18\x03 \x01(\rR\x0evectorsScanned\"\xa1\x01\n" +
	"\x13TransferDataRequest\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\rR\ashardId\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\rR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x04 \x01(\rR\ftargetNodeId\"{\n" +
	"\x14TransferDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x13vectors_transferred\x18\x02 \x01(\x04R\x12vectorsTransferred\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"N\n" +
	"\x10HeartbeatRequest\x12:\n" +
	"\tnode_info\x18\x01 \x01(\v2\x1d.gvdb.proto.internal.NodeInfoR\bnodeInfo\"\xa9\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12'\n" +
	"\x0fassigned_shards\x18\x03 \x03(\rR\x0eassignedShards\x12)\n" +
	"\x10should_rebalance\x18\x04 \x01(\bR\x0fshouldRebalance\"\x19\n" +
	"\x17GetClusterHealthRequest\"\x9e\x02\n" +
	"\x18GetClusterHealthResponse\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.gvdb.proto.internal.NodeInfoR\x05nodes\x12!\n" +
	"\ftotal_shards\x18\x02 \x01(\rR\vtotalShards\x12%\n" +
	"\x0ehealthy_shards\x18\x03 \x01(\rR\rhealthyShards\x12'\n" +
	"\x0fdegraded_shards\x18\x04 \x01(\rR\x0edegradedShards\x12%\n" +
	"\x0ecluster_status\x18\x05 \x01(\tR\rclusterStatus\x123\n" +
	"\x16last_rebalance_unix_ms\x18\x06 \x01(\x03R\x13lastRebalanceUnixMs\"\x16\n" +
	"\x14GetLeaderInfoRequest\"\xa4\x01\n" +
	"\x15GetLeaderInfoResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x05R\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\x12!\n" +
	"\fcurrent_term\x18\x03 \x01(\x04R\vcurrentTerm\x12$\n" +
	"\x0eis_leader_self\x18\x04 \x01(\bR\fisLeaderSelf\"+\n" +
	"\x13GetTimestampRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"d\n" +
	"\x14GetTimestampResponse\x12'\n" +
	"\x0fstart_timestamp\x18\x01 \x01(\x04R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x02 \x01(\x04R\fendTimestamp*\x84\x01\n" +
	"\bNodeType\x12\x15\n" +
	"\x11NODE_TYPE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15NODE_TYPE_COORDINATOR\x10\x01\x12\x17\n" +
	"\x13NODE_TYPE_DATA_NODE\x10\x02\x12\x18\n" +
	"\x14NODE_TYPE_QUERY_NODE\x10\x03\x12\x13\n" +
	"\x0fNODE_TYPE_PROXY\x10\x04*\xb6\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\x13NODE_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14NODE_STATUS_STARTING\x10\x01\x12\x15\n" +
	"\x11NODE_STATUS_READY\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x03\x12\x18\n" +
	"\x14NODE_STATUS_DEGRADED\x10\x04\x12\x14\n" +
	"\x10NODE_STATUS_DOWN\x10\x05\x12\x18\n" +
	"\x14NODE_STATUS_DRAINING\x10\x062\x97\x0e\n" +
	"\x0fInternalService\x12`\n" +
	"\vAssignShard\x12'.gvdb.proto.internal.AssignShardRequest\x1a(.gvdb.proto.internal.AssignShardResponse\x12x\n" +
	"\x13GetShardAssignments\x12/.gvdb.proto.internal.GetShardAssignmentsRequest\x1a0.gvdb.proto.internal.GetShardAssignmentsResponse\x12l\n" +
	"\x0fRebalanceShards\x12+.gvdb.proto.internal.RebalanceShardsRequest\x1a,.gvdb.proto.internal.RebalanceShardsResponse\x12o\n" +
	"\x10ReplicateSegment\x12,.gvdb.proto.internal.ReplicateSegmentRequest\x1a-.gvdb.proto.internal.ReplicateSegmentResponse\x12]\n" +
	"\n" +
	"GetSegment\x12&.gvdb.proto.internal.GetSegmentRequest\x1a'.gvdb.proto.internal.GetSegmentResponse\x12c\n" +
	"\fListSegments\x12(.gvdb.proto.internal.ListSegmentsRequest\x1a).gvdb.proto.internal.ListSegmentsResponse\x12f\n" +
	"\rDeleteSegment\x12).gvdb.proto.internal.DeleteSegmentRequest\x1a*.gvdb.proto.internal.DeleteSegmentResponse\x12f\n" +
	"\rCreateSegment\x12).gvdb.proto.internal.CreateSegmentRequest\x1a*.gvdb.proto.internal.CreateSegmentResponse\x12c\n" +
	"\fSyncMetadata\x12(.gvdb.proto.internal.SyncMetadataRequest\x1a).gvdb.proto.internal.SyncMetadataResponse\x12~\n" +
	"\x15GetCollectionMetadata\x121.gvdb.proto.internal.GetCollectionMetadataRequest\x1a2.gvdb.proto.internal.GetCollectionMetadataResponse\x12]\n" +
	"\n" +
	"RouteQuery\x12&.gvdb.proto.internal.RouteQueryRequest\x1a'.gvdb.proto.internal.RouteQueryResponse\x12r\n" +
	"\x11ExecuteShardQuery\x12-.gvdb.proto.internal.ExecuteShardQueryRequest\x1a..gvdb.proto.internal.ExecuteShardQueryResponse\x12c\n" +
	"\fTransferData\x12(.gvdb.proto.internal.TransferDataRequest\x1a).gvdb.proto.internal.TransferDataResponse\x12Z\n" +
	"\tHeartbeat\x12%.gvdb.proto.internal.HeartbeatRequest\x1a&.gvdb.proto.internal.HeartbeatResponse\x12o\n" +
	"\x10GetClusterHealth\x12,.gvdb.proto.internal.GetClusterHealthRequest\x1a-.gvdb.proto.internal.GetClusterHealthResponse\x12f\n" +
	"\rGetLeaderInfo\x12).gvdb.proto.internal.GetLeaderInfoRequest\x1a*.gvdb.proto.internal.GetLeaderInfoResponse\x12c\n" +
	"\fGetTimestamp\x12(.gvdb.proto.internal.GetTimestampRequest\x1a).gvdb.proto.internal.GetTimestampResponseB\x12Z\x10gvdb/internal/pbb\x06proto3"

var (
	file_internal_proto_rawDescOnce sync.Once
	file_internal_proto_rawDescData []byte
)

func file_internal_proto_rawDescGZIP() []byte {
	file_internal_proto_rawDescOnce.Do(func() {
		file_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)))
	})
	return file_internal_proto_rawDescData
}

var file_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_internal_proto_goTypes = []any{
	(NodeType)(0),                         // 0: gvdb.proto.internal.NodeType
	(NodeStatus)(0),                       // 1: gvdb.proto.internal.NodeStatus
	(*NodeInfo)(nil),                      // 2: gvdb.proto.internal.NodeInfo
	(*ShardAssignment)(nil),               // 3: gvdb.proto.internal.ShardAssignment
	(*AssignShardRequest)(nil),            // 4: gvdb.proto.internal.AssignShardRequest
	(*AssignShardResponse)(nil),           // 5: gvdb.proto.internal.AssignShardResponse
	(*GetShardAssignmentsRequest)(nil),    // 6: gvdb.proto.internal.GetShardAssignmentsRequest
	(*GetShardAssignmentsResponse)(nil),   // 7: gvdb.proto.internal.GetShardAssignmentsResponse
	(*RebalanceShardsRequest)(nil),        // 8: gvdb.proto.internal.RebalanceShardsRequest
	(*RebalanceShardsResponse)(nil),       // 9: gvdb.proto.internal.RebalanceShardsResponse
	(*SegmentInfo)(nil),                   // 10: gvdb.proto.internal.SegmentInfo
	(*ReplicateSegmentRequest)(nil),       // 11: gvdb.proto.internal.ReplicateSegmentRequest
	(*ReplicateSegmentResponse)(nil),      // 12: gvdb.proto.internal.ReplicateSegmentResponse
	(*GetSegmentRequest)(nil),             // 13: gvdb.proto.internal.GetSegmentRequest
	(*GetSegmentResponse)(nil),            // 14: gvdb.proto.internal.GetSegmentResponse
	(*ListSegmentsRequest)(nil),           // 15: gvdb.proto.internal.ListSegmentsRequest
	(*ListSegmentsResponse)(nil),          // 16: gvdb.proto.internal.ListSegmentsResponse
	(*DeleteSegmentRequest)(nil),          // 17: gvdb.proto.internal.DeleteSegmentRequest
	(*DeleteSegmentResponse)(nil),         // 18: gvdb.proto.internal.DeleteSegmentResponse
	(*CreateSegmentRequest)(nil),          // 19: gvdb.proto.internal.CreateSegmentRequest
	(*CreateSegmentResponse)(nil),         // 20: gvdb.proto.internal.CreateSegmentResponse
	(*CollectionMetadata)(nil),            // 21: gvdb.proto.internal.CollectionMetadata
	(*SyncMetadataRequest)(nil),           // 22: gvdb.proto.internal.SyncMetadataRequest
	(*SyncMetadataResponse)(nil),          // 23: gvdb.proto.internal.SyncMetadataResponse
	(*GetCollectionMetadataRequest)(nil),  // 24: gvdb.proto.internal.GetCollectionMetadataRequest
	(*GetCollectionMetadataResponse)(nil), // 25: gvdb.proto.internal.GetCollectionMetadataResponse
	(*RouteQueryRequest)(nil),             // 26: gvdb.proto.internal.RouteQueryRequest
	(*RouteQueryResponse)(nil),            // 27: gvdb.proto.internal.RouteQueryResponse
	(*ExecuteShardQueryRequest)(nil),      // 28: gvdb.proto.internal.ExecuteShardQueryRequest
	(*SearchResult)(nil),                  // 29: gvdb.proto.internal.SearchResult
	(*ExecuteShardQueryResponse)(nil),     // 30: gvdb.proto.internal.ExecuteShardQueryResponse
	(*TransferDataRequest)(nil),           // 31: gvdb.proto.internal.TransferDataRequest
	(*TransferDataResponse)(nil),          // 32: gvdb.proto.internal.TransferDataResponse
	(*HeartbeatRequest)(nil),              // 33: gvdb.proto.internal.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 34: gvdb.proto.internal.HeartbeatResponse
	(*GetClusterHealthRequest)(nil),       // 35: gvdb.proto.internal.GetClusterHealthRequest
	(*GetClusterHealthResponse)(nil),      // 36: gvdb.proto.internal.GetClusterHealthResponse
	(*GetLeaderInfoRequest)(nil),          // 37: gvdb.proto.internal.GetLeaderInfoRequest
	(*GetLeaderInfoResponse)(nil),         // 38: gvdb.proto.internal.GetLeaderInfoResponse
	(*GetTimestampRequest)(nil),           // 39: gvdb.proto.internal.GetTimestampRequest
	(*GetTimestampResponse)(nil),          // 40: gvdb.proto.internal.GetTimestampResponse
	(*Metadata)(nil),                      // 41: gvdb.proto.Metadata
}
var file_internal_proto_depIdxs = []int32{
	0,  // 0: gvdb.proto.internal.NodeInfo.node_type:type_name -> gvdb.proto.internal.NodeType
	1,  // 1: gvdb.proto.internal.NodeInfo.status:type_name -> gvdb.proto.internal.NodeStatus
	3,  // 2: gvdb.proto.internal.GetShardAssignmentsResponse.assignments:type_name -> gvdb.proto.internal.ShardAssignment
	10, // 3: gvdb.proto.internal.ReplicateSegmentRequest.segment_info:type_name -> gvdb.proto.internal.SegmentInfo
	10, // 4: gvdb.proto.internal.GetSegmentResponse.segment_info:type_name -> gvdb.proto.internal.SegmentInfo
	10, // 5: gvdb.proto.internal.ListSegmentsResponse.segments:type_name -> gvdb.proto.internal.SegmentInfo
	3,  // 6: gvdb.proto.internal.CollectionMetadata.shard_assignments:type_name -> gvdb.proto.internal.ShardAssignment
	21, // 7: gvdb.proto.internal.SyncMetadataResponse.collections:type_name -> gvdb.proto.internal.CollectionMetadata
	3,  // 8: gvdb.proto.internal.SyncMetadataResponse.shard_assignments:type_name -> gvdb.proto.internal.ShardAssignment
	21, // 9: gvdb.proto.internal.GetCollectionMetadataResponse.metadata:type_name -> gvdb.proto.internal.CollectionMetadata
	41, // 10: gvdb.proto.internal.SearchResult.metadata:type_name -> gvdb.proto.Metadata
	29, // 11: gvdb.proto.internal.ExecuteShardQueryResponse.results:type_name -> gvdb.proto.internal.SearchResult
	2,  // 12: gvdb.proto.internal.HeartbeatRequest.node_info:type_name -> gvdb.proto.internal.NodeInfo
	2,  // 13: gvdb.proto.internal.GetClusterHealthResponse.nodes:type_name -> gvdb.proto.internal.NodeInfo
	4,  // 14: gvdb.proto.internal.InternalService.AssignShard:input_type -> gvdb.proto.internal.AssignShardRequest
	6,  // 15: gvdb.proto.internal.InternalService.GetShardAssignments:input_type -> gvdb.proto.internal.GetShardAssignmentsRequest
	8,  // 16: gvdb.proto.internal.InternalService.RebalanceShards:input_type -> gvdb.proto.internal.RebalanceShardsRequest
	11, // 17: gvdb.proto.internal.InternalService.ReplicateSegment:input_type -> gvdb.proto.internal.ReplicateSegmentRequest
	13, // 18: gvdb.proto.internal.InternalService.GetSegment:input_type -> gvdb.proto.internal.GetSegmentRequest
	15, // 19: gvdb.proto.internal.InternalService.ListSegments:input_type -> gvdb.proto.internal.ListSegmentsRequest
	17, // 20: gvdb.proto.internal.InternalService.DeleteSegment:input_type -> gvdb.proto.internal.DeleteSegmentRequest
	19, // 21: gvdb.proto.internal.InternalService.CreateSegment:input_type -> gvdb.proto.internal.CreateSegmentRequest
	22, // 22: gvdb.proto.internal.InternalService.SyncMetadata:input_type -> gvdb.proto.internal.SyncMetadataRequest
	24, // 23: gvdb.proto.internal.InternalService.GetCollectionMetadata:input_type -> gvdb.proto.internal.GetCollectionMetadataRequest
	26, // 24: gvdb.proto.internal.InternalService.RouteQuery:input_type -> gvdb.proto.internal.RouteQueryRequest
	28, // 25: gvdb.proto.internal.InternalService.ExecuteShardQuery:input_type -> gvdb.proto.internal.ExecuteShardQueryRequest
	31, // 26: gvdb.proto.internal.InternalService.TransferData:input_type -> gvdb.proto.internal.TransferDataRequest
	33, // 27: gvdb.proto.internal.InternalService.Heartbeat:input_type -> gvdb.proto.internal.HeartbeatRequest
	35, // 28: gvdb.proto.internal.InternalService.GetClusterHealth:input_type -> gvdb.proto.internal.GetClusterHealthRequest
	37, // 29: gvdb.proto.internal.InternalService.GetLeaderInfo:input_type -> gvdb.proto.internal.GetLeaderInfoRequest
	39, // 30: gvdb.proto.internal.InternalService.GetTimestamp:input_type -> gvdb.proto.internal.GetTimestampRequest
	5,  // 31: gvdb.proto.internal.InternalService.AssignShard:output_type -> gvdb.proto.internal.AssignShardResponse
	7,  // 32: gvdb.proto.internal.InternalService.GetShardAssignments:output_type -> gvdb.proto.internal.GetShardAssignmentsResponse
	9,  // 33: gvdb.proto.internal.InternalService.RebalanceShards:output_type -> gvdb.proto.internal.RebalanceShardsResponse
	12, // 34: gvdb.proto.internal.InternalService.ReplicateSegment:output_type -> gvdb.proto.internal.ReplicateSegmentResponse
	14, // 35: gvdb.proto.internal.InternalService.GetSegment:output_type -> gvdb.proto.internal.GetSegmentResponse
	16, // 36: gvdb.proto.internal.InternalService.ListSegments:output_type -> gvdb.proto.internal.ListSegmentsResponse
	18, // 37: gvdb.proto.internal.InternalService.DeleteSegment:output_type -> gvdb.proto.internal.DeleteSegmentResponse
	20, // 38: gvdb.proto.internal.InternalService.CreateSegment:output_type -> gvdb.proto.internal.CreateSegmentResponse
	23, // 39: gvdb.proto.internal.InternalService.SyncMetadata:output_type -> gvdb.proto.internal.SyncMetadataResponse
	25, // 40: gvdb.proto.internal.InternalService.GetCollectionMetadata:output_type -> gvdb.proto.internal.GetCollectionMetadataResponse
	27, // 41: gvdb.proto.internal.InternalService.RouteQuery:output_type -> gvdb.proto.internal.RouteQueryResponse
	30, // 42: gvdb.proto.internal.InternalService.ExecuteShardQuery:output_type -> gvdb.proto.internal.ExecuteShardQueryResponse
	32, // 43: gvdb.proto.internal.InternalService.TransferData:output_type -> gvdb.proto.internal.TransferDataResponse
	34, // 44: gvdb.proto.internal.InternalService.Heartbeat:output_type -> gvdb.proto.internal.HeartbeatResponse
	36, // 45: gvdb.proto.internal.InternalService.GetClusterHealth:output_type -> gvdb.proto.internal.GetClusterHealthResponse
	38, // 46: gvdb.proto.internal.InternalService.GetLeaderInfo:output_type -> gvdb.proto.internal.GetLeaderInfoResponse
	40, // 47: gvdb.proto.internal.InternalService.GetTimestamp:output_type -> gvdb.proto.internal.GetTimestampResponse
	31, // [31:48] is the sub-list for method output_type
	14, // [14:31] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_internal_proto_init() }
func file_internal_proto_init() {
	if File_internal_proto != nil {
		return
	}
	file_vectordb_proto_init()
	file_internal_proto_msgTypes[22].OneofWrappers = []any{
		(*GetCollectionMetadataRequest_CollectionId)(nil),
		(*GetCollectionMetadataRequest_CollectionName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_rawDesc), len(file_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_goTypes,
		DependencyIndexes: file_internal_proto_depIdxs,
		EnumInfos:         file_internal_proto_enumTypes,
		MessageInfos:      file_internal_proto_msgTypes,
	}.Build()
	File_internal_proto = out.File
	file_internal_proto_goTypes = nil
	file_internal_proto_depIdxs = nil
}
