// Copyright 2026 jonathanberhe
// Licensed under the Apache License, Version 2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: internal.proto

package gvdbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalService_AssignShard_FullMethodName           = "/gvdb.proto.internal.InternalService/AssignShard"
	InternalService_GetShardAssignments_FullMethodName   = "/gvdb.proto.internal.InternalService/GetShardAssignments"
	InternalService_RebalanceShards_FullMethodName       = "/gvdb.proto.internal.InternalService/RebalanceShards"
	InternalService_ReplicateSegment_FullMethodName      = "/gvdb.proto.internal.InternalService/ReplicateSegment"
	InternalService_GetSegment_FullMethodName            = "/gvdb.proto.internal.InternalService/GetSegment"
	InternalService_ListSegments_FullMethodName          = "/gvdb.proto.internal.InternalService/ListSegments"
	InternalService_DeleteSegment_FullMethodName         = "/gvdb.proto.internal.InternalService/DeleteSegment"
	InternalService_CreateSegment_FullMethodName         = "/gvdb.proto.internal.InternalService/CreateSegment"
	InternalService_SyncMetadata_FullMethodName          = "/gvdb.proto.internal.InternalService/SyncMetadata"
	InternalService_GetCollectionMetadata_FullMethodName = "/gvdb.proto.internal.InternalService/GetCollectionMetadata"
	InternalService_RouteQuery_FullMethodName            = "/gvdb.proto.internal.InternalService/RouteQuery"
	InternalService_ExecuteShardQuery_FullMethodName     = "/gvdb.proto.internal.InternalService/ExecuteShardQuery"
	InternalService_TransferData_FullMethodName          = "/gvdb.proto.internal.InternalService/TransferData"
	InternalService_Heartbeat_FullMethodName             = "/gvdb.proto.internal.InternalService/Heartbeat"
	InternalService_GetClusterHealth_FullMethodName      = "/gvdb.proto.internal.InternalService/GetClusterHealth"
	InternalService_GetLeaderInfo_FullMethodName         = "/gvdb.proto.internal.InternalService/GetLeaderInfo"
	InternalService_JoinCluster_FullMethodName           = "/gvdb.proto.internal.InternalService/JoinCluster"
	InternalService_RemovePeer_FullMethodName            = "/gvdb.proto.internal.InternalService/RemovePeer"
	InternalService_GetRaftMembership_FullMethodName     = "/gvdb.proto.internal.InternalService/GetRaftMembership"
	InternalService_TransferLeadership_FullMethodName    = "/gvdb.proto.internal.InternalService/TransferLeadership"
	InternalService_PausePrimary_FullMethodName          = "/gvdb.proto.internal.InternalService/PausePrimary"
	InternalService_PreparePromote_FullMethodName        = "/gvdb.proto.internal.InternalService/PreparePromote"
	InternalService_BackupShard_FullMethodName           = "/gvdb.proto.internal.InternalService/BackupShard"
	InternalService_RestoreShard_FullMethodName          = "/gvdb.proto.internal.InternalService/RestoreShard"
	InternalService_FreezeWrites_FullMethodName          = "/gvdb.proto.internal.InternalService/FreezeWrites"
	InternalService_UnfreezeWrites_FullMethodName        = "/gvdb.proto.internal.InternalService/UnfreezeWrites"
	InternalService_GetTimestamp_FullMethodName          = "/gvdb.proto.internal.InternalService/GetTimestamp"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServiceClient interface {
	// Shard management (Coordinator → Data/Query Nodes)
	AssignShard(ctx context.Context, in *AssignShardRequest, opts ...grpc.CallOption) (*AssignShardResponse, error)
	GetShardAssignments(ctx context.Context, in *GetShardAssignmentsRequest, opts ...grpc.CallOption) (*GetShardAssignmentsResponse, error)
	RebalanceShards(ctx context.Context, in *RebalanceShardsRequest, opts ...grpc.CallOption) (*RebalanceShardsResponse, error)
	// Segment replication (Data Node → Data Node)
	ReplicateSegment(ctx context.Context, in *ReplicateSegmentRequest, opts ...grpc.CallOption) (*ReplicateSegmentResponse, error)
	GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error)
	ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error)
	DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error)
	// Segment creation (Coordinator → Data Node)
	CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error)
	// Metadata synchronization (Data/Query Nodes → Coordinator)
	SyncMetadata(ctx context.Context, in *SyncMetadataRequest, opts ...grpc.CallOption) (*SyncMetadataResponse, error)
	GetCollectionMetadata(ctx context.Context, in *GetCollectionMetadataRequest, opts ...grpc.CallOption) (*GetCollectionMetadataResponse, error)
	// Query routing and execution (Proxy → Query Nodes)
	RouteQuery(ctx context.Context, in *RouteQueryRequest, opts ...grpc.CallOption) (*RouteQueryResponse, error)
	ExecuteShardQuery(ctx context.Context, in *ExecuteShardQueryRequest, opts ...grpc.CallOption) (*ExecuteShardQueryResponse, error)
	// Data transfer (for rebalancing)
	TransferData(ctx context.Context, in *TransferDataRequest, opts ...grpc.CallOption) (*TransferDataResponse, error)
	// Health monitoring (All Nodes → Coordinator)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	GetClusterHealth(ctx context.Context, in *GetClusterHealthRequest, opts ...grpc.CallOption) (*GetClusterHealthResponse, error)
	// Leader info (Operator → Coordinator; roadmap 0b.6.D)
	GetLeaderInfo(ctx context.Context, in *GetLeaderInfoRequest, opts ...grpc.CallOption) (*GetLeaderInfoResponse, error)
	// Raft membership changes (Coordinator → Coordinator; roadmap 1.7b)
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	// Raft scale reconciliation (Operator → Coordinator; roadmap 1.8)
	GetRaftMembership(ctx context.Context, in *GetRaftMembershipRequest, opts ...grpc.CallOption) (*GetRaftMembershipResponse, error)
	TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error)
	// Two-phase primary swap (Coordinator → Data Node).
	// PausePrimary stops the old primary accepting writes for the shard;
	// PreparePromote brings the new primary online at the bumped term.
	// Both calls are idempotent so the coordinator can replay on failure.
	PausePrimary(ctx context.Context, in *PausePrimaryRequest, opts ...grpc.CallOption) (*PausePrimaryResponse, error)
	PreparePromote(ctx context.Context, in *PreparePromoteRequest, opts ...grpc.CallOption) (*PreparePromoteResponse, error)
	// Backup and restore orchestration (Coordinator → Data Node).
	// BackupShard / RestoreShard execute the per-shard half of a backup
	// or restore against the data-node's local segment store and the
	// configured IObjectStore. FreezeWrites / UnfreezeWrites bracket the
	// BackupShard call so segment contents are stable for the upload.
	BackupShard(ctx context.Context, in *BackupShardRequest, opts ...grpc.CallOption) (*BackupShardResponse, error)
	RestoreShard(ctx context.Context, in *RestoreShardRequest, opts ...grpc.CallOption) (*RestoreShardResponse, error)
	FreezeWrites(ctx context.Context, in *FreezeWritesRequest, opts ...grpc.CallOption) (*FreezeWritesResponse, error)
	UnfreezeWrites(ctx context.Context, in *UnfreezeWritesRequest, opts ...grpc.CallOption) (*UnfreezeWritesResponse, error)
	// Timestamp oracle (All Nodes → Coordinator)
	GetTimestamp(ctx context.Context, in *GetTimestampRequest, opts ...grpc.CallOption) (*GetTimestampResponse, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) AssignShard(ctx context.Context, in *AssignShardRequest, opts ...grpc.CallOption) (*AssignShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignShardResponse)
	err := c.cc.Invoke(ctx, InternalService_AssignShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetShardAssignments(ctx context.Context, in *GetShardAssignmentsRequest, opts ...grpc.CallOption) (*GetShardAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardAssignmentsResponse)
	err := c.cc.Invoke(ctx, InternalService_GetShardAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RebalanceShards(ctx context.Context, in *RebalanceShardsRequest, opts ...grpc.CallOption) (*RebalanceShardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebalanceShardsResponse)
	err := c.cc.Invoke(ctx, InternalService_RebalanceShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ReplicateSegment(ctx context.Context, in *ReplicateSegmentRequest, opts ...grpc.CallOption) (*ReplicateSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicateSegmentResponse)
	err := c.cc.Invoke(ctx, InternalService_ReplicateSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetSegment(ctx context.Context, in *GetSegmentRequest, opts ...grpc.CallOption) (*GetSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSegmentResponse)
	err := c.cc.Invoke(ctx, InternalService_GetSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ListSegments(ctx context.Context, in *ListSegmentsRequest, opts ...grpc.CallOption) (*ListSegmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSegmentsResponse)
	err := c.cc.Invoke(ctx, InternalService_ListSegments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) DeleteSegment(ctx context.Context, in *DeleteSegmentRequest, opts ...grpc.CallOption) (*DeleteSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSegmentResponse)
	err := c.cc.Invoke(ctx, InternalService_DeleteSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) CreateSegment(ctx context.Context, in *CreateSegmentRequest, opts ...grpc.CallOption) (*CreateSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSegmentResponse)
	err := c.cc.Invoke(ctx, InternalService_CreateSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) SyncMetadata(ctx context.Context, in *SyncMetadataRequest, opts ...grpc.CallOption) (*SyncMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncMetadataResponse)
	err := c.cc.Invoke(ctx, InternalService_SyncMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetCollectionMetadata(ctx context.Context, in *GetCollectionMetadataRequest, opts ...grpc.CallOption) (*GetCollectionMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionMetadataResponse)
	err := c.cc.Invoke(ctx, InternalService_GetCollectionMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RouteQuery(ctx context.Context, in *RouteQueryRequest, opts ...grpc.CallOption) (*RouteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteQueryResponse)
	err := c.cc.Invoke(ctx, InternalService_RouteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) ExecuteShardQuery(ctx context.Context, in *ExecuteShardQueryRequest, opts ...grpc.CallOption) (*ExecuteShardQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteShardQueryResponse)
	err := c.cc.Invoke(ctx, InternalService_ExecuteShardQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) TransferData(ctx context.Context, in *TransferDataRequest, opts ...grpc.CallOption) (*TransferDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferDataResponse)
	err := c.cc.Invoke(ctx, InternalService_TransferData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, InternalService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetClusterHealth(ctx context.Context, in *GetClusterHealthRequest, opts ...grpc.CallOption) (*GetClusterHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterHealthResponse)
	err := c.cc.Invoke(ctx, InternalService_GetClusterHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetLeaderInfo(ctx context.Context, in *GetLeaderInfoRequest, opts ...grpc.CallOption) (*GetLeaderInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderInfoResponse)
	err := c.cc.Invoke(ctx, InternalService_GetLeaderInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, InternalService_JoinCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, InternalService_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetRaftMembership(ctx context.Context, in *GetRaftMembershipRequest, opts ...grpc.CallOption) (*GetRaftMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRaftMembershipResponse)
	err := c.cc.Invoke(ctx, InternalService_GetRaftMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) TransferLeadership(ctx context.Context, in *TransferLeadershipRequest, opts ...grpc.CallOption) (*TransferLeadershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferLeadershipResponse)
	err := c.cc.Invoke(ctx, InternalService_TransferLeadership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) PausePrimary(ctx context.Context, in *PausePrimaryRequest, opts ...grpc.CallOption) (*PausePrimaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PausePrimaryResponse)
	err := c.cc.Invoke(ctx, InternalService_PausePrimary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) PreparePromote(ctx context.Context, in *PreparePromoteRequest, opts ...grpc.CallOption) (*PreparePromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparePromoteResponse)
	err := c.cc.Invoke(ctx, InternalService_PreparePromote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) BackupShard(ctx context.Context, in *BackupShardRequest, opts ...grpc.CallOption) (*BackupShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupShardResponse)
	err := c.cc.Invoke(ctx, InternalService_BackupShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) RestoreShard(ctx context.Context, in *RestoreShardRequest, opts ...grpc.CallOption) (*RestoreShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreShardResponse)
	err := c.cc.Invoke(ctx, InternalService_RestoreShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) FreezeWrites(ctx context.Context, in *FreezeWritesRequest, opts ...grpc.CallOption) (*FreezeWritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeWritesResponse)
	err := c.cc.Invoke(ctx, InternalService_FreezeWrites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) UnfreezeWrites(ctx context.Context, in *UnfreezeWritesRequest, opts ...grpc.CallOption) (*UnfreezeWritesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeWritesResponse)
	err := c.cc.Invoke(ctx, InternalService_UnfreezeWrites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) GetTimestamp(ctx context.Context, in *GetTimestampRequest, opts ...grpc.CallOption) (*GetTimestampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimestampResponse)
	err := c.cc.Invoke(ctx, InternalService_GetTimestamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
type InternalServiceServer interface {
	// Shard management (Coordinator → Data/Query Nodes)
	AssignShard(context.Context, *AssignShardRequest) (*AssignShardResponse, error)
	GetShardAssignments(context.Context, *GetShardAssignmentsRequest) (*GetShardAssignmentsResponse, error)
	RebalanceShards(context.Context, *RebalanceShardsRequest) (*RebalanceShardsResponse, error)
	// Segment replication (Data Node → Data Node)
	ReplicateSegment(context.Context, *ReplicateSegmentRequest) (*ReplicateSegmentResponse, error)
	GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error)
	ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error)
	DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error)
	// Segment creation (Coordinator → Data Node)
	CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error)
	// Metadata synchronization (Data/Query Nodes → Coordinator)
	SyncMetadata(context.Context, *SyncMetadataRequest) (*SyncMetadataResponse, error)
	GetCollectionMetadata(context.Context, *GetCollectionMetadataRequest) (*GetCollectionMetadataResponse, error)
	// Query routing and execution (Proxy → Query Nodes)
	RouteQuery(context.Context, *RouteQueryRequest) (*RouteQueryResponse, error)
	ExecuteShardQuery(context.Context, *ExecuteShardQueryRequest) (*ExecuteShardQueryResponse, error)
	// Data transfer (for rebalancing)
	TransferData(context.Context, *TransferDataRequest) (*TransferDataResponse, error)
	// Health monitoring (All Nodes → Coordinator)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	GetClusterHealth(context.Context, *GetClusterHealthRequest) (*GetClusterHealthResponse, error)
	// Leader info (Operator → Coordinator; roadmap 0b.6.D)
	GetLeaderInfo(context.Context, *GetLeaderInfoRequest) (*GetLeaderInfoResponse, error)
	// Raft membership changes (Coordinator → Coordinator; roadmap 1.7b)
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	// Raft scale reconciliation (Operator → Coordinator; roadmap 1.8)
	GetRaftMembership(context.Context, *GetRaftMembershipRequest) (*GetRaftMembershipResponse, error)
	TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error)
	// Two-phase primary swap (Coordinator → Data Node).
	// PausePrimary stops the old primary accepting writes for the shard;
	// PreparePromote brings the new primary online at the bumped term.
	// Both calls are idempotent so the coordinator can replay on failure.
	PausePrimary(context.Context, *PausePrimaryRequest) (*PausePrimaryResponse, error)
	PreparePromote(context.Context, *PreparePromoteRequest) (*PreparePromoteResponse, error)
	// Backup and restore orchestration (Coordinator → Data Node).
	// BackupShard / RestoreShard execute the per-shard half of a backup
	// or restore against the data-node's local segment store and the
	// configured IObjectStore. FreezeWrites / UnfreezeWrites bracket the
	// BackupShard call so segment contents are stable for the upload.
	BackupShard(context.Context, *BackupShardRequest) (*BackupShardResponse, error)
	RestoreShard(context.Context, *RestoreShardRequest) (*RestoreShardResponse, error)
	FreezeWrites(context.Context, *FreezeWritesRequest) (*FreezeWritesResponse, error)
	UnfreezeWrites(context.Context, *UnfreezeWritesRequest) (*UnfreezeWritesResponse, error)
	// Timestamp oracle (All Nodes → Coordinator)
	GetTimestamp(context.Context, *GetTimestampRequest) (*GetTimestampResponse, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) AssignShard(context.Context, *AssignShardRequest) (*AssignShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignShard not implemented")
}
func (UnimplementedInternalServiceServer) GetShardAssignments(context.Context, *GetShardAssignmentsRequest) (*GetShardAssignmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardAssignments not implemented")
}
func (UnimplementedInternalServiceServer) RebalanceShards(context.Context, *RebalanceShardsRequest) (*RebalanceShardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebalanceShards not implemented")
}
func (UnimplementedInternalServiceServer) ReplicateSegment(context.Context, *ReplicateSegmentRequest) (*ReplicateSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicateSegment not implemented")
}
func (UnimplementedInternalServiceServer) GetSegment(context.Context, *GetSegmentRequest) (*GetSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSegment not implemented")
}
func (UnimplementedInternalServiceServer) ListSegments(context.Context, *ListSegmentsRequest) (*ListSegmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSegments not implemented")
}
func (UnimplementedInternalServiceServer) DeleteSegment(context.Context, *DeleteSegmentRequest) (*DeleteSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSegment not implemented")
}
func (UnimplementedInternalServiceServer) CreateSegment(context.Context, *CreateSegmentRequest) (*CreateSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSegment not implemented")
}
func (UnimplementedInternalServiceServer) SyncMetadata(context.Context, *SyncMetadataRequest) (*SyncMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncMetadata not implemented")
}
func (UnimplementedInternalServiceServer) GetCollectionMetadata(context.Context, *GetCollectionMetadataRequest) (*GetCollectionMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollectionMetadata not implemented")
}
func (UnimplementedInternalServiceServer) RouteQuery(context.Context, *RouteQueryRequest) (*RouteQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteQuery not implemented")
}
func (UnimplementedInternalServiceServer) ExecuteShardQuery(context.Context, *ExecuteShardQueryRequest) (*ExecuteShardQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteShardQuery not implemented")
}
func (UnimplementedInternalServiceServer) TransferData(context.Context, *TransferDataRequest) (*TransferDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferData not implemented")
}
func (UnimplementedInternalServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedInternalServiceServer) GetClusterHealth(context.Context, *GetClusterHealthRequest) (*GetClusterHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterHealth not implemented")
}
func (UnimplementedInternalServiceServer) GetLeaderInfo(context.Context, *GetLeaderInfoRequest) (*GetLeaderInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderInfo not implemented")
}
func (UnimplementedInternalServiceServer) JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedInternalServiceServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedInternalServiceServer) GetRaftMembership(context.Context, *GetRaftMembershipRequest) (*GetRaftMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRaftMembership not implemented")
}
func (UnimplementedInternalServiceServer) TransferLeadership(context.Context, *TransferLeadershipRequest) (*TransferLeadershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferLeadership not implemented")
}
func (UnimplementedInternalServiceServer) PausePrimary(context.Context, *PausePrimaryRequest) (*PausePrimaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PausePrimary not implemented")
}
func (UnimplementedInternalServiceServer) PreparePromote(context.Context, *PreparePromoteRequest) (*PreparePromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreparePromote not implemented")
}
func (UnimplementedInternalServiceServer) BackupShard(context.Context, *BackupShardRequest) (*BackupShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BackupShard not implemented")
}
func (UnimplementedInternalServiceServer) RestoreShard(context.Context, *RestoreShardRequest) (*RestoreShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreShard not implemented")
}
func (UnimplementedInternalServiceServer) FreezeWrites(context.Context, *FreezeWritesRequest) (*FreezeWritesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeWrites not implemented")
}
func (UnimplementedInternalServiceServer) UnfreezeWrites(context.Context, *UnfreezeWritesRequest) (*UnfreezeWritesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfreezeWrites not implemented")
}
func (UnimplementedInternalServiceServer) GetTimestamp(context.Context, *GetTimestampRequest) (*GetTimestampResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimestamp not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_AssignShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).AssignShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_AssignShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).AssignShard(ctx, req.(*AssignShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetShardAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetShardAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetShardAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetShardAssignments(ctx, req.(*GetShardAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RebalanceShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RebalanceShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_RebalanceShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RebalanceShards(ctx, req.(*RebalanceShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ReplicateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ReplicateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ReplicateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ReplicateSegment(ctx, req.(*ReplicateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetSegment(ctx, req.(*GetSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ListSegments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSegmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ListSegments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ListSegments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ListSegments(ctx, req.(*ListSegmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_DeleteSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).DeleteSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_DeleteSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).DeleteSegment(ctx, req.(*DeleteSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_CreateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).CreateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_CreateSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).CreateSegment(ctx, req.(*CreateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_SyncMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).SyncMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_SyncMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).SyncMetadata(ctx, req.(*SyncMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetCollectionMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetCollectionMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetCollectionMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetCollectionMetadata(ctx, req.(*GetCollectionMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RouteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RouteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_RouteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RouteQuery(ctx, req.(*RouteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_ExecuteShardQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteShardQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).ExecuteShardQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_ExecuteShardQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).ExecuteShardQuery(ctx, req.(*ExecuteShardQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_TransferData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).TransferData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_TransferData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).TransferData(ctx, req.(*TransferDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetClusterHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetClusterHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetClusterHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetClusterHealth(ctx, req.(*GetClusterHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetLeaderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetLeaderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetLeaderInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetLeaderInfo(ctx, req.(*GetLeaderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_JoinCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetRaftMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaftMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetRaftMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetRaftMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetRaftMembership(ctx, req.(*GetRaftMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_TransferLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).TransferLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_TransferLeadership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).TransferLeadership(ctx, req.(*TransferLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_PausePrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PausePrimaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).PausePrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_PausePrimary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).PausePrimary(ctx, req.(*PausePrimaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_PreparePromote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreparePromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).PreparePromote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_PreparePromote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).PreparePromote(ctx, req.(*PreparePromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_BackupShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).BackupShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_BackupShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).BackupShard(ctx, req.(*BackupShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_RestoreShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).RestoreShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_RestoreShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).RestoreShard(ctx, req.(*RestoreShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_FreezeWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeWritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).FreezeWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_FreezeWrites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).FreezeWrites(ctx, req.(*FreezeWritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_UnfreezeWrites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeWritesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).UnfreezeWrites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_UnfreezeWrites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).UnfreezeWrites(ctx, req.(*UnfreezeWritesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_GetTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimestampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).GetTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_GetTimestamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).GetTimestamp(ctx, req.(*GetTimestampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gvdb.proto.internal.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignShard",
			Handler:    _InternalService_AssignShard_Handler,
		},
		{
			MethodName: "GetShardAssignments",
			Handler:    _InternalService_GetShardAssignments_Handler,
		},
		{
			MethodName: "RebalanceShards",
			Handler:    _InternalService_RebalanceShards_Handler,
		},
		{
			MethodName: "ReplicateSegment",
			Handler:    _InternalService_ReplicateSegment_Handler,
		},
		{
			MethodName: "GetSegment",
			Handler:    _InternalService_GetSegment_Handler,
		},
		{
			MethodName: "ListSegments",
			Handler:    _InternalService_ListSegments_Handler,
		},
		{
			MethodName: "DeleteSegment",
			Handler:    _InternalService_DeleteSegment_Handler,
		},
		{
			MethodName: "CreateSegment",
			Handler:    _InternalService_CreateSegment_Handler,
		},
		{
			MethodName: "SyncMetadata",
			Handler:    _InternalService_SyncMetadata_Handler,
		},
		{
			MethodName: "GetCollectionMetadata",
			Handler:    _InternalService_GetCollectionMetadata_Handler,
		},
		{
			MethodName: "RouteQuery",
			Handler:    _InternalService_RouteQuery_Handler,
		},
		{
			MethodName: "ExecuteShardQuery",
			Handler:    _InternalService_ExecuteShardQuery_Handler,
		},
		{
			MethodName: "TransferData",
			Handler:    _InternalService_TransferData_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _InternalService_Heartbeat_Handler,
		},
		{
			MethodName: "GetClusterHealth",
			Handler:    _InternalService_GetClusterHealth_Handler,
		},
		{
			MethodName: "GetLeaderInfo",
			Handler:    _InternalService_GetLeaderInfo_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _InternalService_JoinCluster_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _InternalService_RemovePeer_Handler,
		},
		{
			MethodName: "GetRaftMembership",
			Handler:    _InternalService_GetRaftMembership_Handler,
		},
		{
			MethodName: "TransferLeadership",
			Handler:    _InternalService_TransferLeadership_Handler,
		},
		{
			MethodName: "PausePrimary",
			Handler:    _InternalService_PausePrimary_Handler,
		},
		{
			MethodName: "PreparePromote",
			Handler:    _InternalService_PreparePromote_Handler,
		},
		{
			MethodName: "BackupShard",
			Handler:    _InternalService_BackupShard_Handler,
		},
		{
			MethodName: "RestoreShard",
			Handler:    _InternalService_RestoreShard_Handler,
		},
		{
			MethodName: "FreezeWrites",
			Handler:    _InternalService_FreezeWrites_Handler,
		},
		{
			MethodName: "UnfreezeWrites",
			Handler:    _InternalService_UnfreezeWrites_Handler,
		},
		{
			MethodName: "GetTimestamp",
			Handler:    _InternalService_GetTimestamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
