apiVersion: v2
name: gvdb-operator
description: Kubernetes Operator for the GVDB distributed vector database.
type: application
version: 0.32.0 # x-release-please-version
appVersion: "0.32.0" # x-release-please-version
kubeVersion: ">=1.25.0-0"
keywords:
  - operator
  - kubernetes
  - vector-database
  - gvdb
home: https://github.com/JonathanBerhe/gvdb
sources:
  - https://github.com/JonathanBerhe/gvdb
