// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: vectordb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCollectionRequest_MetricType int32

const (
	CreateCollectionRequest_L2            CreateCollectionRequest_MetricType = 0
	CreateCollectionRequest_INNER_PRODUCT CreateCollectionRequest_MetricType = 1
	CreateCollectionRequest_COSINE        CreateCollectionRequest_MetricType = 2
)

// Enum value maps for CreateCollectionRequest_MetricType.
var (
	CreateCollectionRequest_MetricType_name = map[int32]string{
		0: "L2",
		1: "INNER_PRODUCT",
		2: "COSINE",
	}
	CreateCollectionRequest_MetricType_value = map[string]int32{
		"L2":            0,
		"INNER_PRODUCT": 1,
		"COSINE":        2,
	}
)

func (x CreateCollectionRequest_MetricType) Enum() *CreateCollectionRequest_MetricType {
	p := new(CreateCollectionRequest_MetricType)
	*p = x
	return p
}

func (x CreateCollectionRequest_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCollectionRequest_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[0].Descriptor()
}

func (CreateCollectionRequest_MetricType) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[0]
}

func (x CreateCollectionRequest_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCollectionRequest_MetricType.Descriptor instead.
func (CreateCollectionRequest_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{3, 0}
}

type CreateCollectionRequest_IndexType int32

const (
	CreateCollectionRequest_FLAT     CreateCollectionRequest_IndexType = 0
	CreateCollectionRequest_HNSW     CreateCollectionRequest_IndexType = 1
	CreateCollectionRequest_IVF_FLAT CreateCollectionRequest_IndexType = 2
)

// Enum value maps for CreateCollectionRequest_IndexType.
var (
	CreateCollectionRequest_IndexType_name = map[int32]string{
		0: "FLAT",
		1: "HNSW",
		2: "IVF_FLAT",
	}
	CreateCollectionRequest_IndexType_value = map[string]int32{
		"FLAT":     0,
		"HNSW":     1,
		"IVF_FLAT": 2,
	}
)

func (x CreateCollectionRequest_IndexType) Enum() *CreateCollectionRequest_IndexType {
	p := new(CreateCollectionRequest_IndexType)
	*p = x
	return p
}

func (x CreateCollectionRequest_IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCollectionRequest_IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[1].Descriptor()
}

func (CreateCollectionRequest_IndexType) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[1]
}

func (x CreateCollectionRequest_IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCollectionRequest_IndexType.Descriptor instead.
func (CreateCollectionRequest_IndexType) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{3, 1}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_vectordb_proto_enumTypes[2].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_vectordb_proto_enumTypes[2]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{15, 0}
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_vectordb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Vector) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

type VectorWithId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        *Vector                `protobuf:"bytes,2,opt,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorWithId) Reset() {
	*x = VectorWithId{}
	mi := &file_vectordb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorWithId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorWithId) ProtoMessage() {}

func (x *VectorWithId) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorWithId.ProtoReflect.Descriptor instead.
func (*VectorWithId) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{1}
}

func (x *VectorWithId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VectorWithId) GetVector() *Vector {
	if x != nil {
		return x.Vector
	}
	return nil
}

type SearchResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultEntry) Reset() {
	*x = SearchResultEntry{}
	mi := &file_vectordb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultEntry) ProtoMessage() {}

func (x *SearchResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultEntry.ProtoReflect.Descriptor instead.
func (*SearchResultEntry) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResultEntry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResultEntry) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type CreateCollectionRequest struct {
	state          protoimpl.MessageState             `protogen:"open.v1"`
	CollectionName string                             `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Dimension      uint32                             `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Metric         CreateCollectionRequest_MetricType `protobuf:"varint,3,opt,name=metric,proto3,enum=gvdb.proto.CreateCollectionRequest_MetricType" json:"metric,omitempty"`
	IndexType      CreateCollectionRequest_IndexType  `protobuf:"varint,4,opt,name=index_type,json=indexType,proto3,enum=gvdb.proto.CreateCollectionRequest_IndexType" json:"index_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_vectordb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CreateCollectionRequest) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CreateCollectionRequest) GetMetric() CreateCollectionRequest_MetricType {
	if x != nil {
		return x.Metric
	}
	return CreateCollectionRequest_L2
}

func (x *CreateCollectionRequest) GetIndexType() CreateCollectionRequest_IndexType {
	if x != nil {
		return x.IndexType
	}
	return CreateCollectionRequest_FLAT
}

type CreateCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectionId  uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionResponse) Reset() {
	*x = CreateCollectionResponse{}
	mi := &file_vectordb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionResponse) ProtoMessage() {}

func (x *CreateCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionResponse.ProtoReflect.Descriptor instead.
func (*CreateCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCollectionResponse) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CreateCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DropCollectionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DropCollectionRequest) Reset() {
	*x = DropCollectionRequest{}
	mi := &file_vectordb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionRequest) ProtoMessage() {}

func (x *DropCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionRequest.ProtoReflect.Descriptor instead.
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{5}
}

func (x *DropCollectionRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type DropCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCollectionResponse) Reset() {
	*x = DropCollectionResponse{}
	mi := &file_vectordb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCollectionResponse) ProtoMessage() {}

func (x *DropCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCollectionResponse.ProtoReflect.Descriptor instead.
func (*DropCollectionResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{6}
}

func (x *DropCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_vectordb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{7}
}

type CollectionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionId   uint32                 `protobuf:"varint,1,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Dimension      uint32                 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	MetricType     string                 `protobuf:"bytes,4,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	VectorCount    uint64                 `protobuf:"varint,5,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionInfo) Reset() {
	*x = CollectionInfo{}
	mi := &file_vectordb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfo) ProtoMessage() {}

func (x *CollectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfo.ProtoReflect.Descriptor instead.
func (*CollectionInfo) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{8}
}

func (x *CollectionInfo) GetCollectionId() uint32 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *CollectionInfo) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionInfo) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *CollectionInfo) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *CollectionInfo) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*CollectionInfo      `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_vectordb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{9}
}

func (x *ListCollectionsResponse) GetCollections() []*CollectionInfo {
	if x != nil {
		return x.Collections
	}
	return nil
}

type InsertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Vectors        []*VectorWithId        `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_vectordb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{10}
}

func (x *InsertRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *InsertRequest) GetVectors() []*VectorWithId {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InsertedCount uint64                 `protobuf:"varint,1,opt,name=inserted_count,json=insertedCount,proto3" json:"inserted_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_vectordb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{11}
}

func (x *InsertResponse) GetInsertedCount() uint64 {
	if x != nil {
		return x.InsertedCount
	}
	return 0
}

func (x *InsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	QueryVector    *Vector                `protobuf:"bytes,2,opt,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopK           uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_vectordb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchRequest) GetQueryVector() *Vector {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	QueryTimeMs   float32                `protobuf:"fixed32,2,opt,name=query_time_ms,json=queryTimeMs,proto3" json:"query_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_vectordb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetResults() []*SearchResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetQueryTimeMs() float32 {
	if x != nil {
		return x.QueryTimeMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_vectordb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{14}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=gvdb.proto.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_vectordb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_vectordb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{16}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalVectors     uint64                 `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`
	TotalCollections uint64                 `protobuf:"varint,2,opt,name=total_collections,json=totalCollections,proto3" json:"total_collections,omitempty"`
	TotalQueries     uint64                 `protobuf:"varint,3,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	AvgQueryTimeMs   float32                `protobuf:"fixed32,4,opt,name=avg_query_time_ms,json=avgQueryTimeMs,proto3" json:"avg_query_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_vectordb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vectordb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_vectordb_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatsResponse) GetTotalVectors() uint64 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *GetStatsResponse) GetTotalCollections() uint64 {
	if x != nil {
		return x.TotalCollections
	}
	return 0
}

func (x *GetStatsResponse) GetTotalQueries() uint64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *GetStatsResponse) GetAvgQueryTimeMs() float32 {
	if x != nil {
		return x.AvgQueryTimeMs
	}
	return 0
}

var File_vectordb_proto protoreflect.FileDescriptor

const file_vectordb_proto_rawDesc = "" +
	"\n" +
	"\x0evectordb.proto\x12\n" +
	"gvdb.proto\">\n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\"J\n" +
	"\fVectorWithId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12*\n" +
	"\x06vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\x06vector\"?\n" +
	"\x11SearchResultEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"\xda\x02\n" +
	"\x17CreateCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimension\x12F\n" +
	"\x06metric\x18\x03 \x01(\x0e2..gvdb.proto.CreateCollectionRequest.MetricTypeR\x06metric\x12L\n" +
	"\n" +
	"index_type\x18\x04 \x01(\x0e2-.gvdb.proto.CreateCollectionRequest.IndexTypeR\tindexType\"3\n" +
	"\n" +
	"MetricType\x12\x06\n" +
	"\x02L2\x10\x00\x12\x11\n" +
	"\rINNER_PRODUCT\x10\x01\x12\n" +
	"\n" +
	"\x06COSINE\x10\x02\"-\n" +
	"\tIndexType\x12\b\n" +
	"\x04FLAT\x10\x00\x12\b\n" +
	"\x04HNSW\x10\x01\x12\f\n" +
	"\bIVF_FLAT\x10\x02\"Y\n" +
	"\x18CreateCollectionResponse\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x15DropCollectionRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\"2\n" +
	"\x16DropCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x16ListCollectionsRequest\"\xc0\x01\n" +
	"\x0eCollectionInfo\x12#\n" +
	"\rcollection_id\x18\x01 \x01(\rR\fcollectionId\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\rR\tdimension\x12\x1f\n" +
	"\vmetric_type\x18\x04 \x01(\tR\n" +
	"metricType\x12!\n" +
	"\fvector_count\x18\x05 \x01(\x04R\vvectorCount\"W\n" +
	"\x17ListCollectionsResponse\x12<\n" +
	"\vcollections\x18\x01 \x03(\v2\x1a.gvdb.proto.CollectionInfoR\vcollections\"l\n" +
	"\rInsertRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x122\n" +
	"\avectors\x18\x02 \x03(\v2\x18.gvdb.proto.VectorWithIdR\avectors\"Q\n" +
	"\x0eInsertResponse\x12%\n" +
	"\x0einserted_count\x18\x01 \x01(\x04R\rinsertedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\rSearchRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x125\n" +
	"\fquery_vector\x18\x02 \x01(\v2\x12.gvdb.proto.VectorR\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\"m\n" +
	"\x0eSearchResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.gvdb.proto.SearchResultEntryR\aresults\x12\"\n" +
	"\rquery_time_ms\x18\x02 \x01(\x02R\vqueryTimeMs\"\x14\n" +
	"\x12HealthCheckRequest\"\xa4\x01\n" +
	"\x13HealthCheckResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.gvdb.proto.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"\x11\n" +
	"\x0fGetStatsRequest\"\xb4\x01\n" +
	"\x10GetStatsResponse\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x04R\ftotalVectors\x12+\n" +
	"\x11total_collections\x18\x02 \x01(\x04R\x10totalCollections\x12#\n" +
	"\rtotal_queries\x18\x03 \x01(\x04R\ftotalQueries\x12)\n" +
	"\x11avg_query_time_ms\x18\x04 \x01(\x02R\x0eavgQueryTimeMs2\xbe\x04\n" +
	"\x0fVectorDBService\x12]\n" +
	"\x10CreateCollection\x12#.gvdb.proto.CreateCollectionRequest\x1a$.gvdb.proto.CreateCollectionResponse\x12W\n" +
	"\x0eDropCollection\x12!.gvdb.proto.DropCollectionRequest\x1a\".gvdb.proto.DropCollectionResponse\x12Z\n" +
	"\x0fListCollections\x12\".gvdb.proto.ListCollectionsRequest\x1a#.gvdb.proto.ListCollectionsResponse\x12?\n" +
	"\x06Insert\x12\x19.gvdb.proto.InsertRequest\x1a\x1a.gvdb.proto.InsertResponse\x12?\n" +
	"\x06Search\x12\x19.gvdb.proto.SearchRequest\x1a\x1a.gvdb.proto.SearchResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.gvdb.proto.HealthCheckRequest\x1a\x1f.gvdb.proto.HealthCheckResponse\x12E\n" +
	"\bGetStats\x12\x1b.gvdb.proto.GetStatsRequest\x1a\x1c.gvdb.proto.GetStatsResponseB\x1bZ\x19gvdb/integration-tests/pbb\x06proto3"

var (
	file_vectordb_proto_rawDescOnce sync.Once
	file_vectordb_proto_rawDescData []byte
)

func file_vectordb_proto_rawDescGZIP() []byte {
	file_vectordb_proto_rawDescOnce.Do(func() {
		file_vectordb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vectordb_proto_rawDesc), len(file_vectordb_proto_rawDesc)))
	})
	return file_vectordb_proto_rawDescData
}

var file_vectordb_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vectordb_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vectordb_proto_goTypes = []any{
	(CreateCollectionRequest_MetricType)(0), // 0: gvdb.proto.CreateCollectionRequest.MetricType
	(CreateCollectionRequest_IndexType)(0),  // 1: gvdb.proto.CreateCollectionRequest.IndexType
	(HealthCheckResponse_Status)(0),         // 2: gvdb.proto.HealthCheckResponse.Status
	(*Vector)(nil),                          // 3: gvdb.proto.Vector
	(*VectorWithId)(nil),                    // 4: gvdb.proto.VectorWithId
	(*SearchResultEntry)(nil),               // 5: gvdb.proto.SearchResultEntry
	(*CreateCollectionRequest)(nil),         // 6: gvdb.proto.CreateCollectionRequest
	(*CreateCollectionResponse)(nil),        // 7: gvdb.proto.CreateCollectionResponse
	(*DropCollectionRequest)(nil),           // 8: gvdb.proto.DropCollectionRequest
	(*DropCollectionResponse)(nil),          // 9: gvdb.proto.DropCollectionResponse
	(*ListCollectionsRequest)(nil),          // 10: gvdb.proto.ListCollectionsRequest
	(*CollectionInfo)(nil),                  // 11: gvdb.proto.CollectionInfo
	(*ListCollectionsResponse)(nil),         // 12: gvdb.proto.ListCollectionsResponse
	(*InsertRequest)(nil),                   // 13: gvdb.proto.InsertRequest
	(*InsertResponse)(nil),                  // 14: gvdb.proto.InsertResponse
	(*SearchRequest)(nil),                   // 15: gvdb.proto.SearchRequest
	(*SearchResponse)(nil),                  // 16: gvdb.proto.SearchResponse
	(*HealthCheckRequest)(nil),              // 17: gvdb.proto.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 18: gvdb.proto.HealthCheckResponse
	(*GetStatsRequest)(nil),                 // 19: gvdb.proto.GetStatsRequest
	(*GetStatsResponse)(nil),                // 20: gvdb.proto.GetStatsResponse
}
var file_vectordb_proto_depIdxs = []int32{
	3,  // 0: gvdb.proto.VectorWithId.vector:type_name -> gvdb.proto.Vector
	0,  // 1: gvdb.proto.CreateCollectionRequest.metric:type_name -> gvdb.proto.CreateCollectionRequest.MetricType
	1,  // 2: gvdb.proto.CreateCollectionRequest.index_type:type_name -> gvdb.proto.CreateCollectionRequest.IndexType
	11, // 3: gvdb.proto.ListCollectionsResponse.collections:type_name -> gvdb.proto.CollectionInfo
	4,  // 4: gvdb.proto.InsertRequest.vectors:type_name -> gvdb.proto.VectorWithId
	3,  // 5: gvdb.proto.SearchRequest.query_vector:type_name -> gvdb.proto.Vector
	5,  // 6: gvdb.proto.SearchResponse.results:type_name -> gvdb.proto.SearchResultEntry
	2,  // 7: gvdb.proto.HealthCheckResponse.status:type_name -> gvdb.proto.HealthCheckResponse.Status
	6,  // 8: gvdb.proto.VectorDBService.CreateCollection:input_type -> gvdb.proto.CreateCollectionRequest
	8,  // 9: gvdb.proto.VectorDBService.DropCollection:input_type -> gvdb.proto.DropCollectionRequest
	10, // 10: gvdb.proto.VectorDBService.ListCollections:input_type -> gvdb.proto.ListCollectionsRequest
	13, // 11: gvdb.proto.VectorDBService.Insert:input_type -> gvdb.proto.InsertRequest
	15, // 12: gvdb.proto.VectorDBService.Search:input_type -> gvdb.proto.SearchRequest
	17, // 13: gvdb.proto.VectorDBService.HealthCheck:input_type -> gvdb.proto.HealthCheckRequest
	19, // 14: gvdb.proto.VectorDBService.GetStats:input_type -> gvdb.proto.GetStatsRequest
	7,  // 15: gvdb.proto.VectorDBService.CreateCollection:output_type -> gvdb.proto.CreateCollectionResponse
	9,  // 16: gvdb.proto.VectorDBService.DropCollection:output_type -> gvdb.proto.DropCollectionResponse
	12, // 17: gvdb.proto.VectorDBService.ListCollections:output_type -> gvdb.proto.ListCollectionsResponse
	14, // 18: gvdb.proto.VectorDBService.Insert:output_type -> gvdb.proto.InsertResponse
	16, // 19: gvdb.proto.VectorDBService.Search:output_type -> gvdb.proto.SearchResponse
	18, // 20: gvdb.proto.VectorDBService.HealthCheck:output_type -> gvdb.proto.HealthCheckResponse
	20, // 21: gvdb.proto.VectorDBService.GetStats:output_type -> gvdb.proto.GetStatsResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vectordb_proto_init() }
func file_vectordb_proto_init() {
	if File_vectordb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vectordb_proto_rawDesc), len(file_vectordb_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vectordb_proto_goTypes,
		DependencyIndexes: file_vectordb_proto_depIdxs,
		EnumInfos:         file_vectordb_proto_enumTypes,
		MessageInfos:      file_vectordb_proto_msgTypes,
	}.Build()
	File_vectordb_proto = out.File
	file_vectordb_proto_goTypes = nil
	file_vectordb_proto_depIdxs = nil
}
