# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gvdb.pb import vectordb_pb2 as vectordb__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDBServiceStub(object):
    """============================================================================
    VectorDB Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/gvdb.proto.VectorDBService/CreateCollection',
                request_serializer=vectordb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.DropCollection = channel.unary_unary(
                '/gvdb.proto.VectorDBService/DropCollection',
                request_serializer=vectordb__pb2.DropCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DropCollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/gvdb.proto.VectorDBService/ListCollections',
                request_serializer=vectordb__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/gvdb.proto.VectorDBService/Insert',
                request_serializer=vectordb__pb2.InsertRequest.SerializeToString,
                response_deserializer=vectordb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.StreamInsert = channel.stream_unary(
                '/gvdb.proto.VectorDBService/StreamInsert',
                request_serializer=vectordb__pb2.InsertRequest.SerializeToString,
                response_deserializer=vectordb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/gvdb.proto.VectorDBService/Search',
                request_serializer=vectordb__pb2.SearchRequest.SerializeToString,
                response_deserializer=vectordb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gvdb.proto.VectorDBService/Get',
                request_serializer=vectordb__pb2.GetRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/gvdb.proto.VectorDBService/Delete',
                request_serializer=vectordb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UpdateMetadata = channel.unary_unary(
                '/gvdb.proto.VectorDBService/UpdateMetadata',
                request_serializer=vectordb__pb2.UpdateMetadataRequest.SerializeToString,
                response_deserializer=vectordb__pb2.UpdateMetadataResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/gvdb.proto.VectorDBService/HybridSearch',
                request_serializer=vectordb__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=vectordb__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/gvdb.proto.VectorDBService/HealthCheck',
                request_serializer=vectordb__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=vectordb__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/gvdb.proto.VectorDBService/GetStats',
                request_serializer=vectordb__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class VectorDBServiceServicer(object):
    """============================================================================
    VectorDB Service
    ============================================================================

    """

    def CreateCollection(self, request, context):
        """Collection management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Vector operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInsert(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Hybrid search (BM25 + vector)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health and stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=vectordb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'DropCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DropCollection,
                    request_deserializer=vectordb__pb2.DropCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.DropCollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=vectordb__pb2.ListCollectionsRequest.FromString,
                    response_serializer=vectordb__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=vectordb__pb2.InsertRequest.FromString,
                    response_serializer=vectordb__pb2.InsertResponse.SerializeToString,
            ),
            'StreamInsert': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamInsert,
                    request_deserializer=vectordb__pb2.InsertRequest.FromString,
                    response_serializer=vectordb__pb2.InsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vectordb__pb2.SearchRequest.FromString,
                    response_serializer=vectordb__pb2.SearchResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=vectordb__pb2.GetRequest.FromString,
                    response_serializer=vectordb__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=vectordb__pb2.DeleteRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteResponse.SerializeToString,
            ),
            'UpdateMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMetadata,
                    request_deserializer=vectordb__pb2.UpdateMetadataRequest.FromString,
                    response_serializer=vectordb__pb2.UpdateMetadataResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=vectordb__pb2.HybridSearchRequest.FromString,
                    response_serializer=vectordb__pb2.HybridSearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=vectordb__pb2.HealthCheckRequest.FromString,
                    response_serializer=vectordb__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=vectordb__pb2.GetStatsRequest.FromString,
                    response_serializer=vectordb__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gvdb.proto.VectorDBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gvdb.proto.VectorDBService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDBService(object):
    """============================================================================
    VectorDB Service
    ============================================================================

    """

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/CreateCollection',
            vectordb__pb2.CreateCollectionRequest.SerializeToString,
            vectordb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/DropCollection',
            vectordb__pb2.DropCollectionRequest.SerializeToString,
            vectordb__pb2.DropCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/ListCollections',
            vectordb__pb2.ListCollectionsRequest.SerializeToString,
            vectordb__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/Insert',
            vectordb__pb2.InsertRequest.SerializeToString,
            vectordb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gvdb.proto.VectorDBService/StreamInsert',
            vectordb__pb2.InsertRequest.SerializeToString,
            vectordb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/Search',
            vectordb__pb2.SearchRequest.SerializeToString,
            vectordb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/Get',
            vectordb__pb2.GetRequest.SerializeToString,
            vectordb__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/Delete',
            vectordb__pb2.DeleteRequest.SerializeToString,
            vectordb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/UpdateMetadata',
            vectordb__pb2.UpdateMetadataRequest.SerializeToString,
            vectordb__pb2.UpdateMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/HybridSearch',
            vectordb__pb2.HybridSearchRequest.SerializeToString,
            vectordb__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/HealthCheck',
            vectordb__pb2.HealthCheckRequest.SerializeToString,
            vectordb__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gvdb.proto.VectorDBService/GetStats',
            vectordb__pb2.GetStatsRequest.SerializeToString,
            vectordb__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
