apiVersion: v1
kind: Service
metadata:
  name: {{ include "gvdb.dataNode.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gvdb.dataNode.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "gvdb.dataNode.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 50060
      targetPort: 50060
