apiVersion: v1
kind: Service
metadata:
  name: {{ include "gvdb.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gvdb.proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "gvdb.proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.proxy.service.port }}
      targetPort: 50050
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
    - name: metrics
      port: 9050
      targetPort: 9050
